// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: harnessapi/v1/harnessapi.proto

// The Harness API: the client-facing contract of the agentops harness.
//
// A client (a Slack bot, a web app, a CI job) uses it to start an agent
// session, have a human approve it, talk to the agent turn by turn, and read
// everything the session does back off one durable, ordered event log. This
// file is the source of truth for that contract. docs/clients.md is the guide
// to writing a client against it, and `make apistub` builds a conformance
// server that speaks it with no cluster and no credentials.
//
// # Transport
//
// Connect (https://connectrpc.com), over HTTP/2 or HTTP/1.1, with either the
// binary protobuf or the JSON codec. The service is served behind a Pomerium
// route; a client reaches it at that route's URL and presents the credential
// the route asks for (for a workload, its projected ServiceAccount token).
//
// # Terms
//
// These words mean one thing each, everywhere in this file.
//
// client: an application that calls this API — a Slack bot deployment, a web
//
//	app's backend, a CI job. Not a person. One client serves many people.
//
// client id: the identity of a client: the subject of the workload credential
//
//	Pomerium verified on the route (for a Kubernetes workload, its
//	ServiceAccount, e.g. "cluster/system:serviceaccount:agentops:agentops-slackbot").
//	It names the application, never anyone using it.
//
// ClientBinding: the operator's registration of a client id: which agent
//
//	templates it may run and the quotas it runs under. A client without one is
//	refused every verb.
//
// user: a person using an agent through a client — the Slack member who
//
//	mentioned the bot, say. The API never learns who a user is. The client acts
//	on the user's behalf: it relays their words (Prompt.content), their tool-call
//	decisions (RespondPermission), and its own account of what they asked for
//	(CreateSessionRequest.approval_prompt). Which user a conversation belongs to
//	is the client's to track, typically in its conversation_ref.
//
// approver: the person who approves a run on the consent page. The one person
//
//	the platform does identify, by the IdP subject Pomerium authenticates on
//	that page (the approved event's approver_subject). Often the user, but the
//	platform does not assume it: the client decides whom to send the page to.
//	A revive is pinned to the session's first approver.
//
// agent: the AI a session runs, in its own sandbox, as its template defines.
//
// session: one agent working for one conversation, from CreateSession until it
//
//	ends. conversation: whatever the client says the session serves, named by
//	its conversation_ref. turn: one prompt and everything the agent does in
//	answer to it. run: one approved launch — the authorization the approver
//	granted, which the sandbox's credentials derive from; a revive is a new run.
//	workspace: the session's persistent files and transcript, which survive a
//	suspend.
//
// # Identity
//
// Identity is NEVER taken from message fields. The calling client's id comes
// from the X-Pomerium-Jwt-Assertion header the route stamps, and every verb is
// scoped to it: a client sees, and can act on, only the sessions it created. That
// is why no request message carries a client id — a field a client could set
// would be a field a client could lie in. Another client's session is always
// reported as not found, never as forbidden, because saying it exists would
// disclose it. No verb carries a user's identity either; see Terms.
//
// # Errors
//
// A failed call returns a Connect error whose code classifies it, with an
// ErrorInfo detail naming the exact sentinel. Branch on the sentinel; fall back to
// the code when the detail is absent or names something this client does not
// know. See Sentinel for the full list. Every verb returns SENTINEL_FORBIDDEN
// when the calling client has no ClientBinding, i.e. has not been registered to
// use the platform; the per-verb lists below leave that out.
//
// # Retries
//
// Every verb that changes something can be retried without doing it twice:
// CreateSession because a conversation holds one live session (a retry of a
// create that succeeded is SENTINEL_CONFLICT), Prompt by its idempotency_key,
// RespondPermission by its request_id, and EndSession because ending an ended
// session changes nothing.
//
// # Stability
//
// The contract grows only by addition. A client must ignore a field it does not
// know, tolerate an enum value it does not know (a session state, a reason, a
// sentinel), and skip an event whose payload it does not know: a payload added
// later reaches an older client as an Event with no payload set.
package harnessapipbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/pomerium/agentops/harness/api/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HarnessAPIServiceName is the fully-qualified name of the HarnessAPIService service.
	HarnessAPIServiceName = "harnessapi.v1.HarnessAPIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HarnessAPIServiceCreateSessionProcedure is the fully-qualified name of the HarnessAPIService's
	// CreateSession RPC.
	HarnessAPIServiceCreateSessionProcedure = "/harnessapi.v1.HarnessAPIService/CreateSession"
	// HarnessAPIServicePromptProcedure is the fully-qualified name of the HarnessAPIService's Prompt
	// RPC.
	HarnessAPIServicePromptProcedure = "/harnessapi.v1.HarnessAPIService/Prompt"
	// HarnessAPIServiceRespondPermissionProcedure is the fully-qualified name of the
	// HarnessAPIService's RespondPermission RPC.
	HarnessAPIServiceRespondPermissionProcedure = "/harnessapi.v1.HarnessAPIService/RespondPermission"
	// HarnessAPIServiceEndSessionProcedure is the fully-qualified name of the HarnessAPIService's
	// EndSession RPC.
	HarnessAPIServiceEndSessionProcedure = "/harnessapi.v1.HarnessAPIService/EndSession"
	// HarnessAPIServiceGetSessionProcedure is the fully-qualified name of the HarnessAPIService's
	// GetSession RPC.
	HarnessAPIServiceGetSessionProcedure = "/harnessapi.v1.HarnessAPIService/GetSession"
	// HarnessAPIServiceListSessionsProcedure is the fully-qualified name of the HarnessAPIService's
	// ListSessions RPC.
	HarnessAPIServiceListSessionsProcedure = "/harnessapi.v1.HarnessAPIService/ListSessions"
	// HarnessAPIServiceListTemplatesProcedure is the fully-qualified name of the HarnessAPIService's
	// ListTemplates RPC.
	HarnessAPIServiceListTemplatesProcedure = "/harnessapi.v1.HarnessAPIService/ListTemplates"
	// HarnessAPIServiceListEventsProcedure is the fully-qualified name of the HarnessAPIService's
	// ListEvents RPC.
	HarnessAPIServiceListEventsProcedure = "/harnessapi.v1.HarnessAPIService/ListEvents"
	// HarnessAPIServiceSubscribeProcedure is the fully-qualified name of the HarnessAPIService's
	// Subscribe RPC.
	HarnessAPIServiceSubscribeProcedure = "/harnessapi.v1.HarnessAPIService/Subscribe"
)

// HarnessAPIServiceClient is a client for the harnessapi.v1.HarnessAPIService service.
type HarnessAPIServiceClient interface {
	// CreateSession opens a session and starts its launch.
	//
	// It returns as soon as the session exists, in state SESSION_STATE_PENDING;
	// the launch then runs on its own and reports itself on the event log. The
	// client's next job is to deliver the consent-page URL from the
	// approval_required event to the person who should approve — the platform
	// mints the page, but only the client knows who to ask. Nothing runs until
	// that person approves; if nobody does within the approval window, the
	// session ends with END_REASON_NEVER_APPROVED.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT (a required field is blank),
	// SENTINEL_FORBIDDEN (this client has no ClientBinding, or may not run this
	// template), SENTINEL_QUOTA_EXCEEDED (a ClientBinding cap: live sessions,
	// outstanding approvals, or creates per minute), SENTINEL_CONFLICT (the
	// conversation already has a live session), SENTINEL_UNAVAILABLE.
	CreateSession(context.Context, *connect.Request[pb.CreateSessionRequest]) (*connect.Response[pb.CreateSessionResponse], error)
	// Prompt sends one turn to the agent.
	//
	// On a running session it opens a turn and returns its id at once; the turn's
	// output arrives on the event log, every event of it stamped with that turn
	// id, and ends with turn_completed or turn_failed. A second prompt while a
	// turn is still running is accepted, and the turns overlap.
	//
	// On a suspended session it is the revive: a new pod on the same workspace
	// and conversation, a new run, and a fresh approval_required the client must
	// deliver again, pinned to the person who approved the session the first
	// time. A revive counts against the client's quotas like a launch. The log
	// shows a revived event, then the prompt runs as its first turn once
	// approved.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT (empty content), SENTINEL_NOT_FOUND,
	// SENTINEL_INVALID_STATE (the session is in any other state),
	// SENTINEL_NOT_REVIVABLE (suspended, but it cannot be continued — start a new
	// session), SENTINEL_QUOTA_EXCEEDED (a revive over a cap),
	// SENTINEL_UNAVAILABLE.
	Prompt(context.Context, *connect.Request[pb.PromptRequest]) (*connect.Response[pb.PromptResponse], error)
	// RespondPermission answers an outstanding tool-call permission request: the
	// agent asked (a permission_request event) and is blocked until the client
	// relays a choice among the offered options — usually the user's. Who inside
	// the client decided is not something the platform can verify; it trusts the
	// client to relay the decision, and the run's authorization still bounds what
	// any tool call can reach. The decision is recorded as a permission_resolved
	// event.
	//
	// The platform remembers how it resolved a request for ten minutes, so a
	// repeated answer inside that window gets the same result rather than an
	// error. Past it, or for a request that never existed or belongs to a session
	// that is no longer live, the answer is SENTINEL_UNKNOWN_REQUEST.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT (no request_id), SENTINEL_NOT_FOUND,
	// SENTINEL_UNKNOWN_REQUEST, SENTINEL_UNAVAILABLE.
	RespondPermission(context.Context, *connect.Request[pb.RespondPermissionRequest]) (*connect.Response[pb.RespondPermissionResponse], error)
	// EndSession ends a session: its pod and its workspace are released, and the
	// log closes with a session_ended event. Ending a session that has already
	// ended succeeds and changes nothing.
	//
	// Errors: SENTINEL_NOT_FOUND, SENTINEL_UNAVAILABLE.
	EndSession(context.Context, *connect.Request[pb.EndSessionRequest]) (*connect.Response[pb.EndSessionResponse], error)
	// GetSession returns one session, by id or by conversation ref.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT (neither or both of session_id and
	// conversation_ref), SENTINEL_NOT_FOUND, SENTINEL_UNAVAILABLE.
	GetSession(context.Context, *connect.Request[pb.GetSessionRequest]) (*connect.Response[pb.GetSessionResponse], error)
	// ListSessions enumerates the calling client's sessions, newest first, and
	// nobody else's.
	//
	// Errors: SENTINEL_UNAVAILABLE.
	ListSessions(context.Context, *connect.Request[pb.ListSessionsRequest]) (*connect.Response[pb.ListSessionsResponse], error)
	// ListTemplates reports the agent templates this client may run: exactly the
	// names CreateSession accepts in its template field.
	//
	// Errors: SENTINEL_FORBIDDEN (this client has no ClientBinding),
	// SENTINEL_UNAVAILABLE.
	ListTemplates(context.Context, *connect.Request[pb.ListTemplatesRequest]) (*connect.Response[pb.ListTemplatesResponse], error)
	// ListEvents reads one page of a session's event history, in sequence order.
	// Page by passing the last seq you received as after_seq; an empty page means
	// you have everything so far. It is the polling alternative to Subscribe, for
	// a client that cannot hold a stream open.
	//
	// Errors: SENTINEL_NOT_FOUND, SENTINEL_UNAVAILABLE.
	ListEvents(context.Context, *connect.Request[pb.ListEventsRequest]) (*connect.Response[pb.ListEventsResponse], error)
	// Subscribe streams a session's events: everything after after_seq first,
	// then each new event as it is recorded.
	//
	// The first message is always a keepalive, sent once the subscription is
	// accepted; a refusal (SENTINEL_NOT_FOUND and the like) arrives as the
	// stream's error before it. After that the stream carries events and a
	// keepalive every 20 seconds while nothing else happens.
	//
	// Stop on the session_ended EVENT. The server ends the stream cleanly only
	// once the log is finished, and a clean end of stream means exactly that: the
	// log will never grow again. Any other end — an error, a reset, a proxy
	// recycling the connection, several keepalive intervals of silence — means
	// reconnect with after_seq set to the last seq you received. Delivery is
	// at-least-once across reconnects: drop any event whose seq you have already
	// seen.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT, SENTINEL_NOT_FOUND,
	// SENTINEL_UNAVAILABLE.
	Subscribe(context.Context, *connect.Request[pb.SubscribeRequest]) (*connect.ServerStreamForClient[pb.SubscribeResponse], error)
}

// NewHarnessAPIServiceClient constructs a client for the harnessapi.v1.HarnessAPIService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHarnessAPIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HarnessAPIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	harnessAPIServiceMethods := pb.File_harnessapi_v1_harnessapi_proto.Services().ByName("HarnessAPIService").Methods()
	return &harnessAPIServiceClient{
		createSession: connect.NewClient[pb.CreateSessionRequest, pb.CreateSessionResponse](
			httpClient,
			baseURL+HarnessAPIServiceCreateSessionProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		prompt: connect.NewClient[pb.PromptRequest, pb.PromptResponse](
			httpClient,
			baseURL+HarnessAPIServicePromptProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("Prompt")),
			connect.WithClientOptions(opts...),
		),
		respondPermission: connect.NewClient[pb.RespondPermissionRequest, pb.RespondPermissionResponse](
			httpClient,
			baseURL+HarnessAPIServiceRespondPermissionProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("RespondPermission")),
			connect.WithClientOptions(opts...),
		),
		endSession: connect.NewClient[pb.EndSessionRequest, pb.EndSessionResponse](
			httpClient,
			baseURL+HarnessAPIServiceEndSessionProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("EndSession")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[pb.GetSessionRequest, pb.GetSessionResponse](
			httpClient,
			baseURL+HarnessAPIServiceGetSessionProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[pb.ListSessionsRequest, pb.ListSessionsResponse](
			httpClient,
			baseURL+HarnessAPIServiceListSessionsProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		listTemplates: connect.NewClient[pb.ListTemplatesRequest, pb.ListTemplatesResponse](
			httpClient,
			baseURL+HarnessAPIServiceListTemplatesProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("ListTemplates")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[pb.ListEventsRequest, pb.ListEventsResponse](
			httpClient,
			baseURL+HarnessAPIServiceListEventsProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[pb.SubscribeRequest, pb.SubscribeResponse](
			httpClient,
			baseURL+HarnessAPIServiceSubscribeProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// harnessAPIServiceClient implements HarnessAPIServiceClient.
type harnessAPIServiceClient struct {
	createSession     *connect.Client[pb.CreateSessionRequest, pb.CreateSessionResponse]
	prompt            *connect.Client[pb.PromptRequest, pb.PromptResponse]
	respondPermission *connect.Client[pb.RespondPermissionRequest, pb.RespondPermissionResponse]
	endSession        *connect.Client[pb.EndSessionRequest, pb.EndSessionResponse]
	getSession        *connect.Client[pb.GetSessionRequest, pb.GetSessionResponse]
	listSessions      *connect.Client[pb.ListSessionsRequest, pb.ListSessionsResponse]
	listTemplates     *connect.Client[pb.ListTemplatesRequest, pb.ListTemplatesResponse]
	listEvents        *connect.Client[pb.ListEventsRequest, pb.ListEventsResponse]
	subscribe         *connect.Client[pb.SubscribeRequest, pb.SubscribeResponse]
}

// CreateSession calls harnessapi.v1.HarnessAPIService.CreateSession.
func (c *harnessAPIServiceClient) CreateSession(ctx context.Context, req *connect.Request[pb.CreateSessionRequest]) (*connect.Response[pb.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// Prompt calls harnessapi.v1.HarnessAPIService.Prompt.
func (c *harnessAPIServiceClient) Prompt(ctx context.Context, req *connect.Request[pb.PromptRequest]) (*connect.Response[pb.PromptResponse], error) {
	return c.prompt.CallUnary(ctx, req)
}

// RespondPermission calls harnessapi.v1.HarnessAPIService.RespondPermission.
func (c *harnessAPIServiceClient) RespondPermission(ctx context.Context, req *connect.Request[pb.RespondPermissionRequest]) (*connect.Response[pb.RespondPermissionResponse], error) {
	return c.respondPermission.CallUnary(ctx, req)
}

// EndSession calls harnessapi.v1.HarnessAPIService.EndSession.
func (c *harnessAPIServiceClient) EndSession(ctx context.Context, req *connect.Request[pb.EndSessionRequest]) (*connect.Response[pb.EndSessionResponse], error) {
	return c.endSession.CallUnary(ctx, req)
}

// GetSession calls harnessapi.v1.HarnessAPIService.GetSession.
func (c *harnessAPIServiceClient) GetSession(ctx context.Context, req *connect.Request[pb.GetSessionRequest]) (*connect.Response[pb.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// ListSessions calls harnessapi.v1.HarnessAPIService.ListSessions.
func (c *harnessAPIServiceClient) ListSessions(ctx context.Context, req *connect.Request[pb.ListSessionsRequest]) (*connect.Response[pb.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// ListTemplates calls harnessapi.v1.HarnessAPIService.ListTemplates.
func (c *harnessAPIServiceClient) ListTemplates(ctx context.Context, req *connect.Request[pb.ListTemplatesRequest]) (*connect.Response[pb.ListTemplatesResponse], error) {
	return c.listTemplates.CallUnary(ctx, req)
}

// ListEvents calls harnessapi.v1.HarnessAPIService.ListEvents.
func (c *harnessAPIServiceClient) ListEvents(ctx context.Context, req *connect.Request[pb.ListEventsRequest]) (*connect.Response[pb.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// Subscribe calls harnessapi.v1.HarnessAPIService.Subscribe.
func (c *harnessAPIServiceClient) Subscribe(ctx context.Context, req *connect.Request[pb.SubscribeRequest]) (*connect.ServerStreamForClient[pb.SubscribeResponse], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// HarnessAPIServiceHandler is an implementation of the harnessapi.v1.HarnessAPIService service.
type HarnessAPIServiceHandler interface {
	// CreateSession opens a session and starts its launch.
	//
	// It returns as soon as the session exists, in state SESSION_STATE_PENDING;
	// the launch then runs on its own and reports itself on the event log. The
	// client's next job is to deliver the consent-page URL from the
	// approval_required event to the person who should approve — the platform
	// mints the page, but only the client knows who to ask. Nothing runs until
	// that person approves; if nobody does within the approval window, the
	// session ends with END_REASON_NEVER_APPROVED.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT (a required field is blank),
	// SENTINEL_FORBIDDEN (this client has no ClientBinding, or may not run this
	// template), SENTINEL_QUOTA_EXCEEDED (a ClientBinding cap: live sessions,
	// outstanding approvals, or creates per minute), SENTINEL_CONFLICT (the
	// conversation already has a live session), SENTINEL_UNAVAILABLE.
	CreateSession(context.Context, *connect.Request[pb.CreateSessionRequest]) (*connect.Response[pb.CreateSessionResponse], error)
	// Prompt sends one turn to the agent.
	//
	// On a running session it opens a turn and returns its id at once; the turn's
	// output arrives on the event log, every event of it stamped with that turn
	// id, and ends with turn_completed or turn_failed. A second prompt while a
	// turn is still running is accepted, and the turns overlap.
	//
	// On a suspended session it is the revive: a new pod on the same workspace
	// and conversation, a new run, and a fresh approval_required the client must
	// deliver again, pinned to the person who approved the session the first
	// time. A revive counts against the client's quotas like a launch. The log
	// shows a revived event, then the prompt runs as its first turn once
	// approved.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT (empty content), SENTINEL_NOT_FOUND,
	// SENTINEL_INVALID_STATE (the session is in any other state),
	// SENTINEL_NOT_REVIVABLE (suspended, but it cannot be continued — start a new
	// session), SENTINEL_QUOTA_EXCEEDED (a revive over a cap),
	// SENTINEL_UNAVAILABLE.
	Prompt(context.Context, *connect.Request[pb.PromptRequest]) (*connect.Response[pb.PromptResponse], error)
	// RespondPermission answers an outstanding tool-call permission request: the
	// agent asked (a permission_request event) and is blocked until the client
	// relays a choice among the offered options — usually the user's. Who inside
	// the client decided is not something the platform can verify; it trusts the
	// client to relay the decision, and the run's authorization still bounds what
	// any tool call can reach. The decision is recorded as a permission_resolved
	// event.
	//
	// The platform remembers how it resolved a request for ten minutes, so a
	// repeated answer inside that window gets the same result rather than an
	// error. Past it, or for a request that never existed or belongs to a session
	// that is no longer live, the answer is SENTINEL_UNKNOWN_REQUEST.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT (no request_id), SENTINEL_NOT_FOUND,
	// SENTINEL_UNKNOWN_REQUEST, SENTINEL_UNAVAILABLE.
	RespondPermission(context.Context, *connect.Request[pb.RespondPermissionRequest]) (*connect.Response[pb.RespondPermissionResponse], error)
	// EndSession ends a session: its pod and its workspace are released, and the
	// log closes with a session_ended event. Ending a session that has already
	// ended succeeds and changes nothing.
	//
	// Errors: SENTINEL_NOT_FOUND, SENTINEL_UNAVAILABLE.
	EndSession(context.Context, *connect.Request[pb.EndSessionRequest]) (*connect.Response[pb.EndSessionResponse], error)
	// GetSession returns one session, by id or by conversation ref.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT (neither or both of session_id and
	// conversation_ref), SENTINEL_NOT_FOUND, SENTINEL_UNAVAILABLE.
	GetSession(context.Context, *connect.Request[pb.GetSessionRequest]) (*connect.Response[pb.GetSessionResponse], error)
	// ListSessions enumerates the calling client's sessions, newest first, and
	// nobody else's.
	//
	// Errors: SENTINEL_UNAVAILABLE.
	ListSessions(context.Context, *connect.Request[pb.ListSessionsRequest]) (*connect.Response[pb.ListSessionsResponse], error)
	// ListTemplates reports the agent templates this client may run: exactly the
	// names CreateSession accepts in its template field.
	//
	// Errors: SENTINEL_FORBIDDEN (this client has no ClientBinding),
	// SENTINEL_UNAVAILABLE.
	ListTemplates(context.Context, *connect.Request[pb.ListTemplatesRequest]) (*connect.Response[pb.ListTemplatesResponse], error)
	// ListEvents reads one page of a session's event history, in sequence order.
	// Page by passing the last seq you received as after_seq; an empty page means
	// you have everything so far. It is the polling alternative to Subscribe, for
	// a client that cannot hold a stream open.
	//
	// Errors: SENTINEL_NOT_FOUND, SENTINEL_UNAVAILABLE.
	ListEvents(context.Context, *connect.Request[pb.ListEventsRequest]) (*connect.Response[pb.ListEventsResponse], error)
	// Subscribe streams a session's events: everything after after_seq first,
	// then each new event as it is recorded.
	//
	// The first message is always a keepalive, sent once the subscription is
	// accepted; a refusal (SENTINEL_NOT_FOUND and the like) arrives as the
	// stream's error before it. After that the stream carries events and a
	// keepalive every 20 seconds while nothing else happens.
	//
	// Stop on the session_ended EVENT. The server ends the stream cleanly only
	// once the log is finished, and a clean end of stream means exactly that: the
	// log will never grow again. Any other end — an error, a reset, a proxy
	// recycling the connection, several keepalive intervals of silence — means
	// reconnect with after_seq set to the last seq you received. Delivery is
	// at-least-once across reconnects: drop any event whose seq you have already
	// seen.
	//
	// Errors: SENTINEL_INVALID_ARGUMENT, SENTINEL_NOT_FOUND,
	// SENTINEL_UNAVAILABLE.
	Subscribe(context.Context, *connect.Request[pb.SubscribeRequest], *connect.ServerStream[pb.SubscribeResponse]) error
}

// NewHarnessAPIServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHarnessAPIServiceHandler(svc HarnessAPIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	harnessAPIServiceMethods := pb.File_harnessapi_v1_harnessapi_proto.Services().ByName("HarnessAPIService").Methods()
	harnessAPIServiceCreateSessionHandler := connect.NewUnaryHandler(
		HarnessAPIServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(harnessAPIServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServicePromptHandler := connect.NewUnaryHandler(
		HarnessAPIServicePromptProcedure,
		svc.Prompt,
		connect.WithSchema(harnessAPIServiceMethods.ByName("Prompt")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceRespondPermissionHandler := connect.NewUnaryHandler(
		HarnessAPIServiceRespondPermissionProcedure,
		svc.RespondPermission,
		connect.WithSchema(harnessAPIServiceMethods.ByName("RespondPermission")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceEndSessionHandler := connect.NewUnaryHandler(
		HarnessAPIServiceEndSessionProcedure,
		svc.EndSession,
		connect.WithSchema(harnessAPIServiceMethods.ByName("EndSession")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceGetSessionHandler := connect.NewUnaryHandler(
		HarnessAPIServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(harnessAPIServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceListSessionsHandler := connect.NewUnaryHandler(
		HarnessAPIServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(harnessAPIServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceListTemplatesHandler := connect.NewUnaryHandler(
		HarnessAPIServiceListTemplatesProcedure,
		svc.ListTemplates,
		connect.WithSchema(harnessAPIServiceMethods.ByName("ListTemplates")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceListEventsHandler := connect.NewUnaryHandler(
		HarnessAPIServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(harnessAPIServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceSubscribeHandler := connect.NewServerStreamHandler(
		HarnessAPIServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(harnessAPIServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/harnessapi.v1.HarnessAPIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HarnessAPIServiceCreateSessionProcedure:
			harnessAPIServiceCreateSessionHandler.ServeHTTP(w, r)
		case HarnessAPIServicePromptProcedure:
			harnessAPIServicePromptHandler.ServeHTTP(w, r)
		case HarnessAPIServiceRespondPermissionProcedure:
			harnessAPIServiceRespondPermissionHandler.ServeHTTP(w, r)
		case HarnessAPIServiceEndSessionProcedure:
			harnessAPIServiceEndSessionHandler.ServeHTTP(w, r)
		case HarnessAPIServiceGetSessionProcedure:
			harnessAPIServiceGetSessionHandler.ServeHTTP(w, r)
		case HarnessAPIServiceListSessionsProcedure:
			harnessAPIServiceListSessionsHandler.ServeHTTP(w, r)
		case HarnessAPIServiceListTemplatesProcedure:
			harnessAPIServiceListTemplatesHandler.ServeHTTP(w, r)
		case HarnessAPIServiceListEventsProcedure:
			harnessAPIServiceListEventsHandler.ServeHTTP(w, r)
		case HarnessAPIServiceSubscribeProcedure:
			harnessAPIServiceSubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHarnessAPIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHarnessAPIServiceHandler struct{}

func (UnimplementedHarnessAPIServiceHandler) CreateSession(context.Context, *connect.Request[pb.CreateSessionRequest]) (*connect.Response[pb.CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.CreateSession is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) Prompt(context.Context, *connect.Request[pb.PromptRequest]) (*connect.Response[pb.PromptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.Prompt is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) RespondPermission(context.Context, *connect.Request[pb.RespondPermissionRequest]) (*connect.Response[pb.RespondPermissionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.RespondPermission is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) EndSession(context.Context, *connect.Request[pb.EndSessionRequest]) (*connect.Response[pb.EndSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.EndSession is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) GetSession(context.Context, *connect.Request[pb.GetSessionRequest]) (*connect.Response[pb.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.GetSession is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) ListSessions(context.Context, *connect.Request[pb.ListSessionsRequest]) (*connect.Response[pb.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.ListSessions is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) ListTemplates(context.Context, *connect.Request[pb.ListTemplatesRequest]) (*connect.Response[pb.ListTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.ListTemplates is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) ListEvents(context.Context, *connect.Request[pb.ListEventsRequest]) (*connect.Response[pb.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.ListEvents is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) Subscribe(context.Context, *connect.Request[pb.SubscribeRequest], *connect.ServerStream[pb.SubscribeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.Subscribe is not implemented"))
}
