// The Harness API lets a client program start agent sessions and talk to them.
//
// Terms:
//
//   - Client: the program that calls this API, for example a chat bot.
//     Pomerium identifies the client. The API has no concept of an end user.
//   - Session: one agent in one sandbox, with one conversation.
//     A session belongs to the client that created it.
//   - Approver: the person who approves a session before its agent can run.
//     The approver uses the approval_url in the ApprovalRequired event.
//   - Turn: one prompt and the agent's work on it. A turn ends with
//     TurnCompleted or TurnFailed.
//   - Event log: the ordered record of a session. ListEvents and Subscribe
//     read it.
//
// Identity: each request goes through Pomerium. If Pomerium cannot identify
// the client, the server returns the Connect code Unauthenticated.
// A client can see and change only its own sessions. For the session of a
// different client, the server returns SENTINEL_NOT_FOUND.
//
// Errors: a failed request has a Connect code and one error detail of type
// ErrorInfo. The Sentinel tells you the cause. Errors without an ErrorInfo
// are Unauthenticated, Canceled, DeadlineExceeded and Internal.
//
// Retries: a client can send a call again after a transient error if the
// RPC has an idempotency_level, or if the request has a non-empty
// idempotency_key. Do not send other calls again automatically: a lost
// response can hide a change that the server made.
//
// Optional timestamps and durations: if the field is not set, the value is
// not known.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: harnessapi/v1/harnessapi.proto

package harnessapipbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/pomerium/agentops/harness/api/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HarnessAPIServiceName is the fully-qualified name of the HarnessAPIService service.
	HarnessAPIServiceName = "harnessapi.v1.HarnessAPIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HarnessAPIServiceCreateSessionProcedure is the fully-qualified name of the HarnessAPIService's
	// CreateSession RPC.
	HarnessAPIServiceCreateSessionProcedure = "/harnessapi.v1.HarnessAPIService/CreateSession"
	// HarnessAPIServicePromptProcedure is the fully-qualified name of the HarnessAPIService's Prompt
	// RPC.
	HarnessAPIServicePromptProcedure = "/harnessapi.v1.HarnessAPIService/Prompt"
	// HarnessAPIServiceRespondPermissionProcedure is the fully-qualified name of the
	// HarnessAPIService's RespondPermission RPC.
	HarnessAPIServiceRespondPermissionProcedure = "/harnessapi.v1.HarnessAPIService/RespondPermission"
	// HarnessAPIServiceEndSessionProcedure is the fully-qualified name of the HarnessAPIService's
	// EndSession RPC.
	HarnessAPIServiceEndSessionProcedure = "/harnessapi.v1.HarnessAPIService/EndSession"
	// HarnessAPIServiceGetSessionProcedure is the fully-qualified name of the HarnessAPIService's
	// GetSession RPC.
	HarnessAPIServiceGetSessionProcedure = "/harnessapi.v1.HarnessAPIService/GetSession"
	// HarnessAPIServiceListSessionsProcedure is the fully-qualified name of the HarnessAPIService's
	// ListSessions RPC.
	HarnessAPIServiceListSessionsProcedure = "/harnessapi.v1.HarnessAPIService/ListSessions"
	// HarnessAPIServiceListTemplatesProcedure is the fully-qualified name of the HarnessAPIService's
	// ListTemplates RPC.
	HarnessAPIServiceListTemplatesProcedure = "/harnessapi.v1.HarnessAPIService/ListTemplates"
	// HarnessAPIServiceListEventsProcedure is the fully-qualified name of the HarnessAPIService's
	// ListEvents RPC.
	HarnessAPIServiceListEventsProcedure = "/harnessapi.v1.HarnessAPIService/ListEvents"
	// HarnessAPIServiceSubscribeProcedure is the fully-qualified name of the HarnessAPIService's
	// Subscribe RPC.
	HarnessAPIServiceSubscribeProcedure = "/harnessapi.v1.HarnessAPIService/Subscribe"
)

// HarnessAPIServiceClient is a client for the harnessapi.v1.HarnessAPIService service.
type HarnessAPIServiceClient interface {
	// CreateSession starts a new session from a template.
	//
	// The server returns the session in SESSION_STATE_PENDING and starts it in
	// the background. Then an approver must approve the session at the URL in
	// the ApprovalRequired event. After approval, the session goes to
	// SESSION_STATE_RUNNING. Use Subscribe to follow these steps.
	//
	// Errors:
	//   - SENTINEL_INVALID_ARGUMENT: template, conversation_ref or
	//     approval_prompt is empty.
	//   - SENTINEL_FORBIDDEN: the client cannot use the API or the template.
	//   - SENTINEL_NOT_FOUND: the template does not exist.
	//   - SENTINEL_QUOTA_EXCEEDED: the client has too many sessions, or it
	//     creates sessions too fast.
	//   - SENTINEL_CONFLICT: a live session of this client already has the
	//     same conversation_ref.
	CreateSession(context.Context, *pb.CreateSessionRequest) (*pb.CreateSessionResponse, error)
	// Prompt sends a message to the agent and starts a turn.
	//
	// The server returns the turn_id immediately. The agent's work arrives as
	// events with this turn_id.
	//
	// In SESSION_STATE_RUNNING, the turn starts when the session has no other
	// turn in progress. A session runs one turn at a time.
	// In SESSION_STATE_SUSPENDED, the server revives the session first. A
	// revive needs a new approval, so an ApprovalRequired event comes before
	// the turn starts. If the revive fails, the turn gets TurnFailed and the
	// session stays suspended.
	//
	// To retry a Prompt safely, set idempotency_key.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no live session matches the ref.
	//   - SENTINEL_INVALID_ARGUMENT: content is empty.
	//   - SENTINEL_INVALID_STATE: the session is not running or suspended,
	//     or another Prompt is reviving it already.
	//   - SENTINEL_NOT_REVIVABLE: the session is suspended, but the server
	//     cannot revive it. Start a new session.
	//   - SENTINEL_QUOTA_EXCEEDED: a revive is above the client's quota.
	Prompt(context.Context, *pb.PromptRequest) (*pb.PromptResponse, error)
	// RespondPermission answers a PermissionRequest from the agent.
	//
	// If you send the same answer again after the server accepted it, the
	// server returns OK.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no live session matches the ref.
	//   - SENTINEL_INVALID_ARGUMENT: request_id or option_id is empty, or
	//     option_id is not an option of the request. The request stays open.
	//   - SENTINEL_UNKNOWN_REQUEST: the request is not open. It does not
	//     exist, or it has a PermissionResolved event already.
	RespondPermission(context.Context, *pb.RespondPermissionRequest) (*pb.RespondPermissionResponse, error)
	// EndSession stops a live session and removes its sandbox.
	//
	// The server cancels each open permission request with
	// RESOLUTION_SUPERSEDED. Each turn that the server accepted gets
	// TurnCompleted or TurnFailed. Then the server records StateChanged and
	// SessionEnded. No event comes after SessionEnded.
	// If session_id names a session that ended already, EndSession does
	// nothing and returns OK.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no live session matches the ref.
	EndSession(context.Context, *pb.EndSessionRequest) (*pb.EndSessionResponse, error)
	// GetSession returns the current view of one session.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no session matches the ref.
	GetSession(context.Context, *pb.GetSessionRequest) (*pb.GetSessionResponse, error)
	// ListSessions returns the sessions of the client, newest first.
	//
	// The response has all matching sessions. It has no pages.
	ListSessions(context.Context, *pb.ListSessionsRequest) (*pb.ListSessionsResponse, error)
	// ListTemplates returns the templates that the client can use in
	// CreateSession, in name order.
	ListTemplates(context.Context, *pb.ListTemplatesRequest) (*pb.ListTemplatesResponse, error)
	// ListEvents reads one page of a session's event log.
	//
	// The response has the events after after_seq, in seq order. To read the
	// full log, set after_seq to the last seq that you received. Stop when a
	// page has fewer events than the limit.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no session matches the ref.
	ListEvents(context.Context, *pb.ListEventsRequest) (*pb.ListEventsResponse, error)
	// Subscribe sends a session's events as they occur.
	//
	// The stream first sends the events after after_seq from the log. Then it
	// sends new events. Each event comes one time, in seq order. The stream
	// ends with status OK after it sends SessionEnded.
	//
	// The first message is a keepalive. Then the server sends a keepalive
	// every 20 seconds, also between events. If you get no message for
	// 60 seconds, close the stream and subscribe again.
	//
	// To continue after a disconnect, subscribe again with after_seq set to
	// the last seq that you received.
	//
	// The server checks the request before it sends a message. Errors come
	// as the status of the call, not inside the stream.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no session matches the ref.
	Subscribe(context.Context, *pb.SubscribeRequest) (*connect.ServerStreamForClient[pb.SubscribeResponse], error)
}

// NewHarnessAPIServiceClient constructs a client for the harnessapi.v1.HarnessAPIService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHarnessAPIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HarnessAPIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	harnessAPIServiceMethods := pb.File_harnessapi_v1_harnessapi_proto.Services().ByName("HarnessAPIService").Methods()
	return &harnessAPIServiceClient{
		createSession: connect.NewClient[pb.CreateSessionRequest, pb.CreateSessionResponse](
			httpClient,
			baseURL+HarnessAPIServiceCreateSessionProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		prompt: connect.NewClient[pb.PromptRequest, pb.PromptResponse](
			httpClient,
			baseURL+HarnessAPIServicePromptProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("Prompt")),
			connect.WithClientOptions(opts...),
		),
		respondPermission: connect.NewClient[pb.RespondPermissionRequest, pb.RespondPermissionResponse](
			httpClient,
			baseURL+HarnessAPIServiceRespondPermissionProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("RespondPermission")),
			connect.WithClientOptions(opts...),
		),
		endSession: connect.NewClient[pb.EndSessionRequest, pb.EndSessionResponse](
			httpClient,
			baseURL+HarnessAPIServiceEndSessionProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("EndSession")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[pb.GetSessionRequest, pb.GetSessionResponse](
			httpClient,
			baseURL+HarnessAPIServiceGetSessionProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("GetSession")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[pb.ListSessionsRequest, pb.ListSessionsResponse](
			httpClient,
			baseURL+HarnessAPIServiceListSessionsProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("ListSessions")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listTemplates: connect.NewClient[pb.ListTemplatesRequest, pb.ListTemplatesResponse](
			httpClient,
			baseURL+HarnessAPIServiceListTemplatesProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("ListTemplates")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[pb.ListEventsRequest, pb.ListEventsResponse](
			httpClient,
			baseURL+HarnessAPIServiceListEventsProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("ListEvents")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[pb.SubscribeRequest, pb.SubscribeResponse](
			httpClient,
			baseURL+HarnessAPIServiceSubscribeProcedure,
			connect.WithSchema(harnessAPIServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// harnessAPIServiceClient implements HarnessAPIServiceClient.
type harnessAPIServiceClient struct {
	createSession     *connect.Client[pb.CreateSessionRequest, pb.CreateSessionResponse]
	prompt            *connect.Client[pb.PromptRequest, pb.PromptResponse]
	respondPermission *connect.Client[pb.RespondPermissionRequest, pb.RespondPermissionResponse]
	endSession        *connect.Client[pb.EndSessionRequest, pb.EndSessionResponse]
	getSession        *connect.Client[pb.GetSessionRequest, pb.GetSessionResponse]
	listSessions      *connect.Client[pb.ListSessionsRequest, pb.ListSessionsResponse]
	listTemplates     *connect.Client[pb.ListTemplatesRequest, pb.ListTemplatesResponse]
	listEvents        *connect.Client[pb.ListEventsRequest, pb.ListEventsResponse]
	subscribe         *connect.Client[pb.SubscribeRequest, pb.SubscribeResponse]
}

// CreateSession calls harnessapi.v1.HarnessAPIService.CreateSession.
func (c *harnessAPIServiceClient) CreateSession(ctx context.Context, req *pb.CreateSessionRequest) (*pb.CreateSessionResponse, error) {
	response, err := c.createSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Prompt calls harnessapi.v1.HarnessAPIService.Prompt.
func (c *harnessAPIServiceClient) Prompt(ctx context.Context, req *pb.PromptRequest) (*pb.PromptResponse, error) {
	response, err := c.prompt.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RespondPermission calls harnessapi.v1.HarnessAPIService.RespondPermission.
func (c *harnessAPIServiceClient) RespondPermission(ctx context.Context, req *pb.RespondPermissionRequest) (*pb.RespondPermissionResponse, error) {
	response, err := c.respondPermission.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// EndSession calls harnessapi.v1.HarnessAPIService.EndSession.
func (c *harnessAPIServiceClient) EndSession(ctx context.Context, req *pb.EndSessionRequest) (*pb.EndSessionResponse, error) {
	response, err := c.endSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetSession calls harnessapi.v1.HarnessAPIService.GetSession.
func (c *harnessAPIServiceClient) GetSession(ctx context.Context, req *pb.GetSessionRequest) (*pb.GetSessionResponse, error) {
	response, err := c.getSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListSessions calls harnessapi.v1.HarnessAPIService.ListSessions.
func (c *harnessAPIServiceClient) ListSessions(ctx context.Context, req *pb.ListSessionsRequest) (*pb.ListSessionsResponse, error) {
	response, err := c.listSessions.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListTemplates calls harnessapi.v1.HarnessAPIService.ListTemplates.
func (c *harnessAPIServiceClient) ListTemplates(ctx context.Context, req *pb.ListTemplatesRequest) (*pb.ListTemplatesResponse, error) {
	response, err := c.listTemplates.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListEvents calls harnessapi.v1.HarnessAPIService.ListEvents.
func (c *harnessAPIServiceClient) ListEvents(ctx context.Context, req *pb.ListEventsRequest) (*pb.ListEventsResponse, error) {
	response, err := c.listEvents.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Subscribe calls harnessapi.v1.HarnessAPIService.Subscribe.
func (c *harnessAPIServiceClient) Subscribe(ctx context.Context, req *pb.SubscribeRequest) (*connect.ServerStreamForClient[pb.SubscribeResponse], error) {
	return c.subscribe.CallServerStream(ctx, connect.NewRequest(req))
}

// HarnessAPIServiceHandler is an implementation of the harnessapi.v1.HarnessAPIService service.
type HarnessAPIServiceHandler interface {
	// CreateSession starts a new session from a template.
	//
	// The server returns the session in SESSION_STATE_PENDING and starts it in
	// the background. Then an approver must approve the session at the URL in
	// the ApprovalRequired event. After approval, the session goes to
	// SESSION_STATE_RUNNING. Use Subscribe to follow these steps.
	//
	// Errors:
	//   - SENTINEL_INVALID_ARGUMENT: template, conversation_ref or
	//     approval_prompt is empty.
	//   - SENTINEL_FORBIDDEN: the client cannot use the API or the template.
	//   - SENTINEL_NOT_FOUND: the template does not exist.
	//   - SENTINEL_QUOTA_EXCEEDED: the client has too many sessions, or it
	//     creates sessions too fast.
	//   - SENTINEL_CONFLICT: a live session of this client already has the
	//     same conversation_ref.
	CreateSession(context.Context, *pb.CreateSessionRequest) (*pb.CreateSessionResponse, error)
	// Prompt sends a message to the agent and starts a turn.
	//
	// The server returns the turn_id immediately. The agent's work arrives as
	// events with this turn_id.
	//
	// In SESSION_STATE_RUNNING, the turn starts when the session has no other
	// turn in progress. A session runs one turn at a time.
	// In SESSION_STATE_SUSPENDED, the server revives the session first. A
	// revive needs a new approval, so an ApprovalRequired event comes before
	// the turn starts. If the revive fails, the turn gets TurnFailed and the
	// session stays suspended.
	//
	// To retry a Prompt safely, set idempotency_key.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no live session matches the ref.
	//   - SENTINEL_INVALID_ARGUMENT: content is empty.
	//   - SENTINEL_INVALID_STATE: the session is not running or suspended,
	//     or another Prompt is reviving it already.
	//   - SENTINEL_NOT_REVIVABLE: the session is suspended, but the server
	//     cannot revive it. Start a new session.
	//   - SENTINEL_QUOTA_EXCEEDED: a revive is above the client's quota.
	Prompt(context.Context, *pb.PromptRequest) (*pb.PromptResponse, error)
	// RespondPermission answers a PermissionRequest from the agent.
	//
	// If you send the same answer again after the server accepted it, the
	// server returns OK.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no live session matches the ref.
	//   - SENTINEL_INVALID_ARGUMENT: request_id or option_id is empty, or
	//     option_id is not an option of the request. The request stays open.
	//   - SENTINEL_UNKNOWN_REQUEST: the request is not open. It does not
	//     exist, or it has a PermissionResolved event already.
	RespondPermission(context.Context, *pb.RespondPermissionRequest) (*pb.RespondPermissionResponse, error)
	// EndSession stops a live session and removes its sandbox.
	//
	// The server cancels each open permission request with
	// RESOLUTION_SUPERSEDED. Each turn that the server accepted gets
	// TurnCompleted or TurnFailed. Then the server records StateChanged and
	// SessionEnded. No event comes after SessionEnded.
	// If session_id names a session that ended already, EndSession does
	// nothing and returns OK.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no live session matches the ref.
	EndSession(context.Context, *pb.EndSessionRequest) (*pb.EndSessionResponse, error)
	// GetSession returns the current view of one session.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no session matches the ref.
	GetSession(context.Context, *pb.GetSessionRequest) (*pb.GetSessionResponse, error)
	// ListSessions returns the sessions of the client, newest first.
	//
	// The response has all matching sessions. It has no pages.
	ListSessions(context.Context, *pb.ListSessionsRequest) (*pb.ListSessionsResponse, error)
	// ListTemplates returns the templates that the client can use in
	// CreateSession, in name order.
	ListTemplates(context.Context, *pb.ListTemplatesRequest) (*pb.ListTemplatesResponse, error)
	// ListEvents reads one page of a session's event log.
	//
	// The response has the events after after_seq, in seq order. To read the
	// full log, set after_seq to the last seq that you received. Stop when a
	// page has fewer events than the limit.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no session matches the ref.
	ListEvents(context.Context, *pb.ListEventsRequest) (*pb.ListEventsResponse, error)
	// Subscribe sends a session's events as they occur.
	//
	// The stream first sends the events after after_seq from the log. Then it
	// sends new events. Each event comes one time, in seq order. The stream
	// ends with status OK after it sends SessionEnded.
	//
	// The first message is a keepalive. Then the server sends a keepalive
	// every 20 seconds, also between events. If you get no message for
	// 60 seconds, close the stream and subscribe again.
	//
	// To continue after a disconnect, subscribe again with after_seq set to
	// the last seq that you received.
	//
	// The server checks the request before it sends a message. Errors come
	// as the status of the call, not inside the stream.
	//
	// Errors:
	//   - SENTINEL_NOT_FOUND: no session matches the ref.
	Subscribe(context.Context, *pb.SubscribeRequest, *connect.ServerStream[pb.SubscribeResponse]) error
}

// NewHarnessAPIServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHarnessAPIServiceHandler(svc HarnessAPIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	harnessAPIServiceMethods := pb.File_harnessapi_v1_harnessapi_proto.Services().ByName("HarnessAPIService").Methods()
	harnessAPIServiceCreateSessionHandler := connect.NewUnaryHandlerSimple(
		HarnessAPIServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(harnessAPIServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServicePromptHandler := connect.NewUnaryHandlerSimple(
		HarnessAPIServicePromptProcedure,
		svc.Prompt,
		connect.WithSchema(harnessAPIServiceMethods.ByName("Prompt")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceRespondPermissionHandler := connect.NewUnaryHandlerSimple(
		HarnessAPIServiceRespondPermissionProcedure,
		svc.RespondPermission,
		connect.WithSchema(harnessAPIServiceMethods.ByName("RespondPermission")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceEndSessionHandler := connect.NewUnaryHandlerSimple(
		HarnessAPIServiceEndSessionProcedure,
		svc.EndSession,
		connect.WithSchema(harnessAPIServiceMethods.ByName("EndSession")),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceGetSessionHandler := connect.NewUnaryHandlerSimple(
		HarnessAPIServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(harnessAPIServiceMethods.ByName("GetSession")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceListSessionsHandler := connect.NewUnaryHandlerSimple(
		HarnessAPIServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(harnessAPIServiceMethods.ByName("ListSessions")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceListTemplatesHandler := connect.NewUnaryHandlerSimple(
		HarnessAPIServiceListTemplatesProcedure,
		svc.ListTemplates,
		connect.WithSchema(harnessAPIServiceMethods.ByName("ListTemplates")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceListEventsHandler := connect.NewUnaryHandlerSimple(
		HarnessAPIServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(harnessAPIServiceMethods.ByName("ListEvents")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	harnessAPIServiceSubscribeHandler := connect.NewServerStreamHandlerSimple(
		HarnessAPIServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(harnessAPIServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/harnessapi.v1.HarnessAPIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HarnessAPIServiceCreateSessionProcedure:
			harnessAPIServiceCreateSessionHandler.ServeHTTP(w, r)
		case HarnessAPIServicePromptProcedure:
			harnessAPIServicePromptHandler.ServeHTTP(w, r)
		case HarnessAPIServiceRespondPermissionProcedure:
			harnessAPIServiceRespondPermissionHandler.ServeHTTP(w, r)
		case HarnessAPIServiceEndSessionProcedure:
			harnessAPIServiceEndSessionHandler.ServeHTTP(w, r)
		case HarnessAPIServiceGetSessionProcedure:
			harnessAPIServiceGetSessionHandler.ServeHTTP(w, r)
		case HarnessAPIServiceListSessionsProcedure:
			harnessAPIServiceListSessionsHandler.ServeHTTP(w, r)
		case HarnessAPIServiceListTemplatesProcedure:
			harnessAPIServiceListTemplatesHandler.ServeHTTP(w, r)
		case HarnessAPIServiceListEventsProcedure:
			harnessAPIServiceListEventsHandler.ServeHTTP(w, r)
		case HarnessAPIServiceSubscribeProcedure:
			harnessAPIServiceSubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHarnessAPIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHarnessAPIServiceHandler struct{}

func (UnimplementedHarnessAPIServiceHandler) CreateSession(context.Context, *pb.CreateSessionRequest) (*pb.CreateSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.CreateSession is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) Prompt(context.Context, *pb.PromptRequest) (*pb.PromptResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.Prompt is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) RespondPermission(context.Context, *pb.RespondPermissionRequest) (*pb.RespondPermissionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.RespondPermission is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) EndSession(context.Context, *pb.EndSessionRequest) (*pb.EndSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.EndSession is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) GetSession(context.Context, *pb.GetSessionRequest) (*pb.GetSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.GetSession is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) ListSessions(context.Context, *pb.ListSessionsRequest) (*pb.ListSessionsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.ListSessions is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) ListTemplates(context.Context, *pb.ListTemplatesRequest) (*pb.ListTemplatesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.ListTemplates is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) ListEvents(context.Context, *pb.ListEventsRequest) (*pb.ListEventsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.ListEvents is not implemented"))
}

func (UnimplementedHarnessAPIServiceHandler) Subscribe(context.Context, *pb.SubscribeRequest, *connect.ServerStream[pb.SubscribeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("harnessapi.v1.HarnessAPIService.Subscribe is not implemented"))
}
