// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: runner/v1/runner.proto

package runnerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRunnerService_Run_FullMethodName = "/runner.v1.AgentRunnerService/Run"
)

// AgentRunnerServiceClient is the client API for AgentRunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentRunnerService starts the agent process and connects its stdio.
//
// The agent-runner serves this service. It is PID 1 of the agent container.
// It listens on a unix socket in the pod. The sidecar is its only client. The
// kernel delivers the bytes on the socket in order and without loss, so frames
// have no sequence numbers or acks.
type AgentRunnerServiceClient interface {
	// Run starts one agent and connects its stdio to the stream. The runner runs
	// one agent at a time. While an agent runs, it refuses a second Run.
	//
	// When the stream closes, the runner sends TERM to the agent. After 10
	// seconds, it sends KILL.
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunnerClientFrame, RunnerServerFrame], error)
}

type agentRunnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRunnerServiceClient(cc grpc.ClientConnInterface) AgentRunnerServiceClient {
	return &agentRunnerServiceClient{cc}
}

func (c *agentRunnerServiceClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunnerClientFrame, RunnerServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRunnerService_ServiceDesc.Streams[0], AgentRunnerService_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunnerClientFrame, RunnerServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRunnerService_RunClient = grpc.BidiStreamingClient[RunnerClientFrame, RunnerServerFrame]

// AgentRunnerServiceServer is the server API for AgentRunnerService service.
// All implementations must embed UnimplementedAgentRunnerServiceServer
// for forward compatibility.
//
// AgentRunnerService starts the agent process and connects its stdio.
//
// The agent-runner serves this service. It is PID 1 of the agent container.
// It listens on a unix socket in the pod. The sidecar is its only client. The
// kernel delivers the bytes on the socket in order and without loss, so frames
// have no sequence numbers or acks.
type AgentRunnerServiceServer interface {
	// Run starts one agent and connects its stdio to the stream. The runner runs
	// one agent at a time. While an agent runs, it refuses a second Run.
	//
	// When the stream closes, the runner sends TERM to the agent. After 10
	// seconds, it sends KILL.
	Run(grpc.BidiStreamingServer[RunnerClientFrame, RunnerServerFrame]) error
	mustEmbedUnimplementedAgentRunnerServiceServer()
}

// UnimplementedAgentRunnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRunnerServiceServer struct{}

func (UnimplementedAgentRunnerServiceServer) Run(grpc.BidiStreamingServer[RunnerClientFrame, RunnerServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAgentRunnerServiceServer) mustEmbedUnimplementedAgentRunnerServiceServer() {}
func (UnimplementedAgentRunnerServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRunnerServiceServer will
// result in compilation errors.
type UnsafeAgentRunnerServiceServer interface {
	mustEmbedUnimplementedAgentRunnerServiceServer()
}

func RegisterAgentRunnerServiceServer(s grpc.ServiceRegistrar, srv AgentRunnerServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRunnerService_ServiceDesc, srv)
}

func _AgentRunnerService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentRunnerServiceServer).Run(&grpc.GenericServerStream[RunnerClientFrame, RunnerServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRunnerService_RunServer = grpc.BidiStreamingServer[RunnerClientFrame, RunnerServerFrame]

// AgentRunnerService_ServiceDesc is the grpc.ServiceDesc for AgentRunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runner.v1.AgentRunnerService",
	HandlerType: (*AgentRunnerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _AgentRunnerService_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "runner/v1/runner.proto",
}
