// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: runner/v1/runner.proto

package runnerpb

import (
	pb "github.com/pomerium/agentops/harness/internal/agentlink/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*RunnerClientFrame_Spawn
	//	*RunnerClientFrame_Join
	//	*RunnerClientFrame_Replay
	//	*RunnerClientFrame_Ack
	//	*RunnerClientFrame_Prompt
	//	*RunnerClientFrame_Permission
	//	*RunnerClientFrame_Stop
	Msg           isRunnerClientFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerClientFrame) Reset() {
	*x = RunnerClientFrame{}
	mi := &file_runner_v1_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerClientFrame) ProtoMessage() {}

func (x *RunnerClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerClientFrame.ProtoReflect.Descriptor instead.
func (*RunnerClientFrame) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerClientFrame) GetMsg() isRunnerClientFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RunnerClientFrame) GetSpawn() *Spawn {
	if x != nil {
		if x, ok := x.Msg.(*RunnerClientFrame_Spawn); ok {
			return x.Spawn
		}
	}
	return nil
}

func (x *RunnerClientFrame) GetJoin() *Join {
	if x != nil {
		if x, ok := x.Msg.(*RunnerClientFrame_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *RunnerClientFrame) GetReplay() *Replay {
	if x != nil {
		if x, ok := x.Msg.(*RunnerClientFrame_Replay); ok {
			return x.Replay
		}
	}
	return nil
}

func (x *RunnerClientFrame) GetAck() *pb.AgentIOAck {
	if x != nil {
		if x, ok := x.Msg.(*RunnerClientFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *RunnerClientFrame) GetPrompt() *pb.Prompt {
	if x != nil {
		if x, ok := x.Msg.(*RunnerClientFrame_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

func (x *RunnerClientFrame) GetPermission() *pb.PermissionDecision {
	if x != nil {
		if x, ok := x.Msg.(*RunnerClientFrame_Permission); ok {
			return x.Permission
		}
	}
	return nil
}

func (x *RunnerClientFrame) GetStop() *Stop {
	if x != nil {
		if x, ok := x.Msg.(*RunnerClientFrame_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

type isRunnerClientFrame_Msg interface {
	isRunnerClientFrame_Msg()
}

type RunnerClientFrame_Spawn struct {
	// The first frame, if the agent does not run yet. The runner runs
	// `/bin/sh -lc 'exec ${ACP_AGENT_CMD:-acp-agent}'`, and then it opens the
	// ACP session. If a session with the same stream_id runs, Spawn joins it.
	// If a session with a different stream_id runs, the stream fails with
	// ALREADY_EXISTS.
	Spawn *Spawn `protobuf:"bytes,1,opt,name=spawn,proto3,oneof"`
}

type RunnerClientFrame_Join struct {
	// The first frame, to join the session that runs. If there is no session,
	// the stream fails with NOT_FOUND.
	Join *Join `protobuf:"bytes,4,opt,name=join,proto3,oneof"`
}

type RunnerClientFrame_Replay struct {
	// Starts the events. The runner sends ReplayStart, then the events after
	// Replay.after, and then each new event. Before Replay, the runner sends no
	// events. Send Replay again after each new AgentIO stream.
	Replay *Replay `protobuf:"bytes,5,opt,name=replay,proto3,oneof"`
}

type RunnerClientFrame_Ack struct {
	Ack *pb.AgentIOAck `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

type RunnerClientFrame_Prompt struct {
	Prompt *pb.Prompt `protobuf:"bytes,7,opt,name=prompt,proto3,oneof"`
}

type RunnerClientFrame_Permission struct {
	Permission *pb.PermissionDecision `protobuf:"bytes,8,opt,name=permission,proto3,oneof"`
}

type RunnerClientFrame_Stop struct {
	// Stops the agent: TERM, then KILL after 10 seconds. The runner then sends
	// AgentExited as the last event.
	Stop *Stop `protobuf:"bytes,9,opt,name=stop,proto3,oneof"`
}

func (*RunnerClientFrame_Spawn) isRunnerClientFrame_Msg() {}

func (*RunnerClientFrame_Join) isRunnerClientFrame_Msg() {}

func (*RunnerClientFrame_Replay) isRunnerClientFrame_Msg() {}

func (*RunnerClientFrame_Ack) isRunnerClientFrame_Msg() {}

func (*RunnerClientFrame_Prompt) isRunnerClientFrame_Msg() {}

func (*RunnerClientFrame_Permission) isRunnerClientFrame_Msg() {}

func (*RunnerClientFrame_Stop) isRunnerClientFrame_Msg() {}

type RunnerServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*RunnerServerFrame_Started
	//	*RunnerServerFrame_ReplayStart
	//	*RunnerServerFrame_Event
	Msg           isRunnerServerFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerServerFrame) Reset() {
	*x = RunnerServerFrame{}
	mi := &file_runner_v1_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerServerFrame) ProtoMessage() {}

func (x *RunnerServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerServerFrame.ProtoReflect.Descriptor instead.
func (*RunnerServerFrame) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RunnerServerFrame) GetMsg() isRunnerServerFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RunnerServerFrame) GetStarted() *Started {
	if x != nil {
		if x, ok := x.Msg.(*RunnerServerFrame_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *RunnerServerFrame) GetReplayStart() *ReplayStart {
	if x != nil {
		if x, ok := x.Msg.(*RunnerServerFrame_ReplayStart); ok {
			return x.ReplayStart
		}
	}
	return nil
}

func (x *RunnerServerFrame) GetEvent() *pb.AgentEvent {
	if x != nil {
		if x, ok := x.Msg.(*RunnerServerFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isRunnerServerFrame_Msg interface {
	isRunnerServerFrame_Msg()
}

type RunnerServerFrame_Started struct {
	Started *Started `protobuf:"bytes,1,opt,name=started,proto3,oneof"` // the first frame, after Spawn or Join
}

type RunnerServerFrame_ReplayStart struct {
	ReplayStart *ReplayStart `protobuf:"bytes,5,opt,name=replay_start,json=replayStart,proto3,oneof"` // the first frame after each Replay
}

type RunnerServerFrame_Event struct {
	Event *pb.AgentEvent `protobuf:"bytes,6,opt,name=event,proto3,oneof"`
}

func (*RunnerServerFrame_Started) isRunnerServerFrame_Msg() {}

func (*RunnerServerFrame_ReplayStart) isRunnerServerFrame_Msg() {}

func (*RunnerServerFrame_Event) isRunnerServerFrame_Msg() {}

type Spawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      []byte                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Session       *pb.SessionParams      `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spawn) Reset() {
	*x = Spawn{}
	mi := &file_runner_v1_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spawn) ProtoMessage() {}

func (x *Spawn) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spawn.ProtoReflect.Descriptor instead.
func (*Spawn) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{2}
}

func (x *Spawn) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *Spawn) GetSession() *pb.SessionParams {
	if x != nil {
		return x.Session
	}
	return nil
}

type Join struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_runner_v1_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{3}
}

type Replay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The last event that the manager consumed.
	After         uint64 `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replay) Reset() {
	*x = Replay{}
	mi := &file_runner_v1_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replay) ProtoMessage() {}

func (x *Replay) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replay.ProtoReflect.Descriptor instead.
func (*Replay) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{4}
}

func (x *Replay) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

type Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stop) Reset() {
	*x = Stop{}
	mi := &file_runner_v1_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{5}
}

type Started struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int64                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	StreamId      []byte                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Started) Reset() {
	*x = Started{}
	mi := &file_runner_v1_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Started) ProtoMessage() {}

func (x *Started) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Started.ProtoReflect.Descriptor instead.
func (*Started) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{6}
}

func (x *Started) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Started) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

type ReplayStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *pb.AgentState         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayStart) Reset() {
	*x = ReplayStart{}
	mi := &file_runner_v1_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayStart) ProtoMessage() {}

func (x *ReplayStart) ProtoReflect() protoreflect.Message {
	mi := &file_runner_v1_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayStart.ProtoReflect.Descriptor instead.
func (*ReplayStart) Descriptor() ([]byte, []int) {
	return file_runner_v1_runner_proto_rawDescGZIP(), []int{7}
}

func (x *ReplayStart) GetState() *pb.AgentState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_runner_v1_runner_proto protoreflect.FileDescriptor

const file_runner_v1_runner_proto_rawDesc = "" +
	"\n" +
	"\x16runner/v1/runner.proto\x12\trunner.v1\x1a\x1cagentlink/v1/agentlink.proto\"\xed\x02\n" +
	"\x11RunnerClientFrame\x12(\n" +
	"\x05spawn\x18\x01 \x01(\v2\x10.runner.v1.SpawnH\x00R\x05spawn\x12%\n" +
	"\x04join\x18\x04 \x01(\v2\x0f.runner.v1.JoinH\x00R\x04join\x12+\n" +
	"\x06replay\x18\x05 \x01(\v2\x11.runner.v1.ReplayH\x00R\x06replay\x12,\n" +
	"\x03ack\x18\x06 \x01(\v2\x18.agentlink.v1.AgentIOAckH\x00R\x03ack\x12.\n" +
	"\x06prompt\x18\a \x01(\v2\x14.agentlink.v1.PromptH\x00R\x06prompt\x12B\n" +
	"\n" +
	"permission\x18\b \x01(\v2 .agentlink.v1.PermissionDecisionH\x00R\n" +
	"permission\x12%\n" +
	"\x04stop\x18\t \x01(\v2\x0f.runner.v1.StopH\x00R\x04stopB\x05\n" +
	"\x03msgJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"\xcb\x01\n" +
	"\x11RunnerServerFrame\x12.\n" +
	"\astarted\x18\x01 \x01(\v2\x12.runner.v1.StartedH\x00R\astarted\x12;\n" +
	"\freplay_start\x18\x05 \x01(\v2\x16.runner.v1.ReplayStartH\x00R\vreplayStart\x120\n" +
	"\x05event\x18\x06 \x01(\v2\x18.agentlink.v1.AgentEventH\x00R\x05eventB\x05\n" +
	"\x03msgJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"[\n" +
	"\x05Spawn\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\fR\bstreamId\x125\n" +
	"\asession\x18\x02 \x01(\v2\x1b.agentlink.v1.SessionParamsR\asession\"\x06\n" +
	"\x04Join\"\x1e\n" +
	"\x06Replay\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x04R\x05after\"\x06\n" +
	"\x04Stop\"8\n" +
	"\aStarted\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\fR\bstreamId\"=\n" +
	"\vReplayStart\x12.\n" +
	"\x05state\x18\x01 \x01(\v2\x18.agentlink.v1.AgentStateR\x05state2[\n" +
	"\x12AgentRunnerService\x12E\n" +
	"\x03Run\x12\x1c.runner.v1.RunnerClientFrame\x1a\x1c.runner.v1.RunnerServerFrame(\x010\x01BBZ@github.com/pomerium/agentops/harness/internal/runner/pb;runnerpbb\x06proto3"

var (
	file_runner_v1_runner_proto_rawDescOnce sync.Once
	file_runner_v1_runner_proto_rawDescData []byte
)

func file_runner_v1_runner_proto_rawDescGZIP() []byte {
	file_runner_v1_runner_proto_rawDescOnce.Do(func() {
		file_runner_v1_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_v1_runner_proto_rawDesc), len(file_runner_v1_runner_proto_rawDesc)))
	})
	return file_runner_v1_runner_proto_rawDescData
}

var file_runner_v1_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_runner_v1_runner_proto_goTypes = []any{
	(*RunnerClientFrame)(nil),     // 0: runner.v1.RunnerClientFrame
	(*RunnerServerFrame)(nil),     // 1: runner.v1.RunnerServerFrame
	(*Spawn)(nil),                 // 2: runner.v1.Spawn
	(*Join)(nil),                  // 3: runner.v1.Join
	(*Replay)(nil),                // 4: runner.v1.Replay
	(*Stop)(nil),                  // 5: runner.v1.Stop
	(*Started)(nil),               // 6: runner.v1.Started
	(*ReplayStart)(nil),           // 7: runner.v1.ReplayStart
	(*pb.AgentIOAck)(nil),         // 8: agentlink.v1.AgentIOAck
	(*pb.Prompt)(nil),             // 9: agentlink.v1.Prompt
	(*pb.PermissionDecision)(nil), // 10: agentlink.v1.PermissionDecision
	(*pb.AgentEvent)(nil),         // 11: agentlink.v1.AgentEvent
	(*pb.SessionParams)(nil),      // 12: agentlink.v1.SessionParams
	(*pb.AgentState)(nil),         // 13: agentlink.v1.AgentState
}
var file_runner_v1_runner_proto_depIdxs = []int32{
	2,  // 0: runner.v1.RunnerClientFrame.spawn:type_name -> runner.v1.Spawn
	3,  // 1: runner.v1.RunnerClientFrame.join:type_name -> runner.v1.Join
	4,  // 2: runner.v1.RunnerClientFrame.replay:type_name -> runner.v1.Replay
	8,  // 3: runner.v1.RunnerClientFrame.ack:type_name -> agentlink.v1.AgentIOAck
	9,  // 4: runner.v1.RunnerClientFrame.prompt:type_name -> agentlink.v1.Prompt
	10, // 5: runner.v1.RunnerClientFrame.permission:type_name -> agentlink.v1.PermissionDecision
	5,  // 6: runner.v1.RunnerClientFrame.stop:type_name -> runner.v1.Stop
	6,  // 7: runner.v1.RunnerServerFrame.started:type_name -> runner.v1.Started
	7,  // 8: runner.v1.RunnerServerFrame.replay_start:type_name -> runner.v1.ReplayStart
	11, // 9: runner.v1.RunnerServerFrame.event:type_name -> agentlink.v1.AgentEvent
	12, // 10: runner.v1.Spawn.session:type_name -> agentlink.v1.SessionParams
	13, // 11: runner.v1.ReplayStart.state:type_name -> agentlink.v1.AgentState
	0,  // 12: runner.v1.AgentRunnerService.Run:input_type -> runner.v1.RunnerClientFrame
	1,  // 13: runner.v1.AgentRunnerService.Run:output_type -> runner.v1.RunnerServerFrame
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_runner_v1_runner_proto_init() }
func file_runner_v1_runner_proto_init() {
	if File_runner_v1_runner_proto != nil {
		return
	}
	file_runner_v1_runner_proto_msgTypes[0].OneofWrappers = []any{
		(*RunnerClientFrame_Spawn)(nil),
		(*RunnerClientFrame_Join)(nil),
		(*RunnerClientFrame_Replay)(nil),
		(*RunnerClientFrame_Ack)(nil),
		(*RunnerClientFrame_Prompt)(nil),
		(*RunnerClientFrame_Permission)(nil),
		(*RunnerClientFrame_Stop)(nil),
	}
	file_runner_v1_runner_proto_msgTypes[1].OneofWrappers = []any{
		(*RunnerServerFrame_Started)(nil),
		(*RunnerServerFrame_ReplayStart)(nil),
		(*RunnerServerFrame_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_v1_runner_proto_rawDesc), len(file_runner_v1_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_v1_runner_proto_goTypes,
		DependencyIndexes: file_runner_v1_runner_proto_depIdxs,
		MessageInfos:      file_runner_v1_runner_proto_msgTypes,
	}.Build()
	File_runner_v1_runner_proto = out.File
	file_runner_v1_runner_proto_goTypes = nil
	file_runner_v1_runner_proto_depIdxs = nil
}
