// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type McpCredential struct {
	SlackUserID      string `json:"slack_user_id"`
	ServerName       string `json:"server_name"`
	ServerUrl        string `json:"server_url"`
	AccessToken      string `json:"access_token"`
	RefreshToken     string `json:"refresh_token"`
	TokenType        string `json:"token_type"`
	Expiry           int64  `json:"expiry"`
	AuthUrl          string `json:"auth_url"`
	TokenUrl         string `json:"token_url"`
	ClientID         string `json:"client_id"`
	ClientSecret     string `json:"client_secret"`
	Scopes           string `json:"scopes"`
	RegistrationJson string `json:"registration_json"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}

type OauthFlow struct {
	FlowID               string `json:"flow_id"`
	State                string `json:"state"`
	SlackUserID          string `json:"slack_user_id"`
	SlackTeamID          string `json:"slack_team_id"`
	SlackChannelID       string `json:"slack_channel_id"`
	SlackThreadTs        string `json:"slack_thread_ts"`
	ServerName           string `json:"server_name"`
	ServerUrl            string `json:"server_url"`
	WorkflowName         string `json:"workflow_name"`
	AuthUrl              string `json:"auth_url"`
	TokenUrl             string `json:"token_url"`
	RegistrationEndpoint string `json:"registration_endpoint"`
	ClientID             string `json:"client_id"`
	ClientSecret         string `json:"client_secret"`
	Scopes               string `json:"scopes"`
	PkceVerifier         string `json:"pkce_verifier"`
	RedirectUri          string `json:"redirect_uri"`
	CreatedAt            int64  `json:"created_at"`
	ExpiresAt            int64  `json:"expires_at"`
}

type Session struct {
	ID               string `json:"id"`
	SlackChannelID   string `json:"slack_channel_id"`
	SlackThreadTs    string `json:"slack_thread_ts"`
	SlackUserID      string `json:"slack_user_id"`
	WorkflowName     string `json:"workflow_name"`
	SandboxClaimName string `json:"sandbox_claim_name"`
	SandboxName      string `json:"sandbox_name"`
	AcpSessionID     string `json:"acp_session_id"`
	Status           string `json:"status"`
	SlackResponseUrl string `json:"slack_response_url"`
	InitialPrompt    string `json:"initial_prompt"`
	CreatedAt        int64  `json:"created_at"`
	UpdatedAt        int64  `json:"updated_at"`
}
