apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slackbot.fullname" . }}-channels
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slackbot.labels" . | nindent 4 }}
data:
  channels.yaml: |
    channels:
      {{- range $channel, $template := .Values.slack.channels }}
      {{ $channel | quote }}: {{ $template | quote }}
      {{- end }}
    {{- with .Values.slack.defaultChannelTemplate }}
    default: {{ . | quote }}
    {{- end }}
