{{- if not .Values.slack.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slackbot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slackbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  SLACK_SIGNING_SECRET: {{ .Values.slack.signingSecret | quote }}
  SLACK_BOT_TOKEN: {{ .Values.slack.botToken | quote }}
{{- end }}
