apiVersion: v1
kind: Service
metadata:
  name: {{ include "slackbot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slackbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "slackbot.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
