// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: harnessapi/v1/harnessapi.proto

package harnessapipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorInfo travels as a Connect error detail and names the typed error the
// platform actually raised.
//
// The Connect code alone is not enough: several sentinels map onto the same code
// (a not-found session and an unknown permission request are both NotFound-ish,
// forbidden and quota-exceeded are both refusals), and a client that branches on
// errors.Is needs the sentinel back, not an approximation of it. Carrying the
// name makes the mapping injective, so an error round-trips through the wire
// and still matches the same errors.Is check on the far side.
type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sentinel is the Go sentinel's name, e.g. "ErrNotRevivable". Unknown names
	// are tolerated: a client that does not recognize one falls back to the code.
	Sentinel string `protobuf:"bytes,1,opt,name=sentinel,proto3" json:"sentinel,omitempty"`
	// detail is the human-readable elaboration the sentinel was wrapped with.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetSentinel() string {
	if x != nil {
		return x.Sentinel
	}
	return ""
}

func (x *ErrorInfo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// SessionRef addresses a session by id or by conversation, always within the
// calling client. Exactly one of session_id/conversation_ref must be set.
//
// It carries no client_id: the caller's identity is the verified assertion's,
// and a field here would only ever be a lie waiting to be believed.
type SessionRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConversationRef string                 `protobuf:"bytes,2,opt,name=conversation_ref,json=conversationRef,proto3" json:"conversation_ref,omitempty"`
	// include_terminal makes a lookup by conversation_ref return the most recent
	// session the conversation had even if it has ended. Verbs that act on a
	// session ignore it.
	IncludeTerminal bool `protobuf:"varint,3,opt,name=include_terminal,json=includeTerminal,proto3" json:"include_terminal,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionRef) Reset() {
	*x = SessionRef{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRef) ProtoMessage() {}

func (x *SessionRef) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRef.ProtoReflect.Descriptor instead.
func (*SessionRef) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{1}
}

func (x *SessionRef) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionRef) GetConversationRef() string {
	if x != nil {
		return x.ConversationRef
	}
	return ""
}

func (x *SessionRef) GetIncludeTerminal() bool {
	if x != nil {
		return x.IncludeTerminal
	}
	return false
}

// SessionView is what a client sees of a session. State and reason-shaped fields
// are strings, not enums: the vocabularies are additive and a client must
// tolerate a value it does not know rather than fail to parse the message.
type SessionView struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationRef string                 `protobuf:"bytes,2,opt,name=conversation_ref,json=conversationRef,proto3" json:"conversation_ref,omitempty"`
	State           string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Template        string                 `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	// last_seq is the newest event on the session's log: where a client that has
	// rendered nothing yet starts reading, so it does not replay the conversation.
	LastSeq       int64 `protobuf:"varint,5,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionView) Reset() {
	*x = SessionView{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionView) ProtoMessage() {}

func (x *SessionView) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionView.ProtoReflect.Descriptor instead.
func (*SessionView) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{2}
}

func (x *SessionView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionView) GetConversationRef() string {
	if x != nil {
		return x.ConversationRef
	}
	return ""
}

func (x *SessionView) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SessionView) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SessionView) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

// Event is one entry on a session's durable, ordered log.
//
// type is a string and payload is the raw JSON body — deliberately, and this is
// load-bearing. The event set is additive-only with unknown-type tolerance, and
// the log promises byte-identical replay; a proto enum would reject a type this
// build has not heard of, and a oneof would re-encode a payload the store holds
// verbatim. Both would break the contract at the transport, which is the one
// place it must not break.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	TurnId        string                 `protobuf:"bytes,4,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// TemplateSummary is one entry of ListTemplates: what a client may run.
type TemplateSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateSummary) Reset() {
	*x = TemplateSummary{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSummary) ProtoMessage() {}

func (x *TemplateSummary) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSummary.ProtoReflect.Descriptor instead.
func (*TemplateSummary) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{4}
}

func (x *TemplateSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSessionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Template             string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	ConversationRef      string                 `protobuf:"bytes,2,opt,name=conversation_ref,json=conversationRef,proto3" json:"conversation_ref,omitempty"`
	ParentSessionId      string                 `protobuf:"bytes,3,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	ApprovalPrompt       string                 `protobuf:"bytes,4,opt,name=approval_prompt,json=approvalPrompt,proto3" json:"approval_prompt,omitempty"`
	InitialPrompt        string                 `protobuf:"bytes,5,opt,name=initial_prompt,json=initialPrompt,proto3" json:"initial_prompt,omitempty"`
	SystemPromptAppendix string                 `protobuf:"bytes,6,opt,name=system_prompt_appendix,json=systemPromptAppendix,proto3" json:"system_prompt_appendix,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *CreateSessionRequest) GetConversationRef() string {
	if x != nil {
		return x.ConversationRef
	}
	return ""
}

func (x *CreateSessionRequest) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *CreateSessionRequest) GetApprovalPrompt() string {
	if x != nil {
		return x.ApprovalPrompt
	}
	return ""
}

func (x *CreateSessionRequest) GetInitialPrompt() string {
	if x != nil {
		return x.InitialPrompt
	}
	return ""
}

func (x *CreateSessionRequest) GetSystemPromptAppendix() string {
	if x != nil {
		return x.SystemPromptAppendix
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionView           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSessionResponse) GetSession() *SessionView {
	if x != nil {
		return x.Session
	}
	return nil
}

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *SessionRef            `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{7}
}

func (x *PromptRequest) GetRef() *SessionRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *PromptRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TurnId        string                 `protobuf:"bytes,1,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{8}
}

func (x *PromptResponse) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

type RespondPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *SessionRef            `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OptionId      string                 `protobuf:"bytes,3,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondPermissionRequest) Reset() {
	*x = RespondPermissionRequest{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondPermissionRequest) ProtoMessage() {}

func (x *RespondPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondPermissionRequest.ProtoReflect.Descriptor instead.
func (*RespondPermissionRequest) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{9}
}

func (x *RespondPermissionRequest) GetRef() *SessionRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *RespondPermissionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RespondPermissionRequest) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

type RespondPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondPermissionResponse) Reset() {
	*x = RespondPermissionResponse{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondPermissionResponse) ProtoMessage() {}

func (x *RespondPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondPermissionResponse.ProtoReflect.Descriptor instead.
func (*RespondPermissionResponse) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{10}
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *SessionRef            `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{11}
}

func (x *EndSessionRequest) GetRef() *SessionRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *EndSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{12}
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *SessionRef            `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{13}
}

func (x *GetSessionRequest) GetRef() *SessionRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionView           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{14}
}

func (x *GetSessionResponse) GetSession() *SessionView {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// live_only drops ended and interrupted sessions.
	LiveOnly bool `protobuf:"varint,1,opt,name=live_only,json=liveOnly,proto3" json:"live_only,omitempty"`
	// updated_since returns only sessions touched at or after this instant. It is
	// what a client's own reconciliation sweep pages on: "which of my sessions
	// moved since I last looked", which live_only cannot express because a session
	// that just went terminal is exactly the one worth hearing about.
	UpdatedSince  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_since,json=updatedSince,proto3" json:"updated_since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{15}
}

func (x *ListSessionsRequest) GetLiveOnly() bool {
	if x != nil {
		return x.LiveOnly
	}
	return false
}

func (x *ListSessionsRequest) GetUpdatedSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedSince
	}
	return nil
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionView         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{16}
}

func (x *ListSessionsResponse) GetSessions() []*SessionView {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{17}
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateSummary     `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{18}
}

func (x *ListTemplatesResponse) GetTemplates() []*TemplateSummary {
	if x != nil {
		return x.Templates
	}
	return nil
}

type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *SessionRef            `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// after_seq returns events strictly after this sequence; 0 starts at the
	// beginning.
	AfterSeq int64 `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	// limit caps the page; 0 means the server default.
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{19}
}

func (x *ListEventsRequest) GetRef() *SessionRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ListEventsRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{20}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *SessionRef            `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// after_seq resumes: history at or before it is not replayed, history after it
	// is, so a reconnecting client picks up exactly where it stopped.
	AfterSeq      int64 `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{21}
}

func (x *SubscribeRequest) GetRef() *SessionRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *SubscribeRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

// SubscribeResponse carries either a session event or a keepalive.
//
// The FIRST message of every subscription is a keepalive, sent as soon as the
// server has accepted the subscription. That is what makes opening one a
// synchronous operation: a server-streaming call returns before the server has
// done anything, so without an opening message a client cannot tell "subscribed"
// from "refused" until an event happens to arrive — which for a quiet session is
// never, and for another client's session would be silence instead of a denial.
//
// The keepalive is not decoration. HTTP/2 PINGs terminate at each hop, so a
// proxy in the path can hold a subscription open that has been dead upstream for
// minutes; an application-level tick is the only liveness signal that traverses
// the whole path. Clients discard keepalives and treat several missed intervals
// as a dead stream worth reconnecting with after_seq.
type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Keepalive     bool                   `protobuf:"varint,2,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harnessapi_v1_harnessapi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_harnessapi_v1_harnessapi_proto_rawDescGZIP(), []int{22}
}

func (x *SubscribeResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SubscribeResponse) GetKeepalive() bool {
	if x != nil {
		return x.Keepalive
	}
	return false
}

var File_harnessapi_v1_harnessapi_proto protoreflect.FileDescriptor

const file_harnessapi_v1_harnessapi_proto_rawDesc = "" +
	"\n" +
	"\x1eharnessapi/v1/harnessapi.proto\x12\rharnessapi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n" +
	"\tErrorInfo\x12\x1a\n" +
	"\bsentinel\x18\x01 \x01(\tR\bsentinel\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x81\x01\n" +
	"\n" +
	"SessionRef\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12)\n" +
	"\x10conversation_ref\x18\x02 \x01(\tR\x0fconversationRef\x12)\n" +
	"\x10include_terminal\x18\x03 \x01(\bR\x0fincludeTerminal\"\x95\x01\n" +
	"\vSessionView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10conversation_ref\x18\x02 \x01(\tR\x0fconversationRef\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\btemplate\x18\x04 \x01(\tR\btemplate\x12\x19\n" +
	"\blast_seq\x18\x05 \x01(\x03R\alastSeq\"\xb9\x01\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x17\n" +
	"\aturn_id\x18\x04 \x01(\tR\x06turnId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"G\n" +
	"\x0fTemplateSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x8f\x02\n" +
	"\x14CreateSessionRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12)\n" +
	"\x10conversation_ref\x18\x02 \x01(\tR\x0fconversationRef\x12*\n" +
	"\x11parent_session_id\x18\x03 \x01(\tR\x0fparentSessionId\x12'\n" +
	"\x0fapproval_prompt\x18\x04 \x01(\tR\x0eapprovalPrompt\x12%\n" +
	"\x0einitial_prompt\x18\x05 \x01(\tR\rinitialPrompt\x124\n" +
	"\x16system_prompt_appendix\x18\x06 \x01(\tR\x14systemPromptAppendix\"M\n" +
	"\x15CreateSessionResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x1a.harnessapi.v1.SessionViewR\asession\"V\n" +
	"\rPromptRequest\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x19.harnessapi.v1.SessionRefR\x03ref\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\")\n" +
	"\x0ePromptResponse\x12\x17\n" +
	"\aturn_id\x18\x01 \x01(\tR\x06turnId\"\x83\x01\n" +
	"\x18RespondPermissionRequest\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x19.harnessapi.v1.SessionRefR\x03ref\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1b\n" +
	"\toption_id\x18\x03 \x01(\tR\boptionId\"\x1b\n" +
	"\x19RespondPermissionResponse\"X\n" +
	"\x11EndSessionRequest\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x19.harnessapi.v1.SessionRefR\x03ref\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x14\n" +
	"\x12EndSessionResponse\"@\n" +
	"\x11GetSessionRequest\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x19.harnessapi.v1.SessionRefR\x03ref\"J\n" +
	"\x12GetSessionResponse\x124\n" +
	"\asession\x18\x01 \x01(\v2\x1a.harnessapi.v1.SessionViewR\asession\"s\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\tlive_only\x18\x01 \x01(\bR\bliveOnly\x12?\n" +
	"\rupdated_since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fupdatedSince\"N\n" +
	"\x14ListSessionsResponse\x126\n" +
	"\bsessions\x18\x01 \x03(\v2\x1a.harnessapi.v1.SessionViewR\bsessions\"\x16\n" +
	"\x14ListTemplatesRequest\"U\n" +
	"\x15ListTemplatesResponse\x12<\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1e.harnessapi.v1.TemplateSummaryR\ttemplates\"s\n" +
	"\x11ListEventsRequest\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x19.harnessapi.v1.SessionRefR\x03ref\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x03R\bafterSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"B\n" +
	"\x12ListEventsResponse\x12,\n" +
	"\x06events\x18\x01 \x03(\v2\x14.harnessapi.v1.EventR\x06events\"\\\n" +
	"\x10SubscribeRequest\x12+\n" +
	"\x03ref\x18\x01 \x01(\v2\x19.harnessapi.v1.SessionRefR\x03ref\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x03R\bafterSeq\"]\n" +
	"\x11SubscribeResponse\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.harnessapi.v1.EventR\x05event\x12\x1c\n" +
	"\tkeepalive\x18\x02 \x01(\bR\tkeepalive2\x9e\x06\n" +
	"\x11HarnessAPIService\x12Z\n" +
	"\rCreateSession\x12#.harnessapi.v1.CreateSessionRequest\x1a$.harnessapi.v1.CreateSessionResponse\x12E\n" +
	"\x06Prompt\x12\x1c.harnessapi.v1.PromptRequest\x1a\x1d.harnessapi.v1.PromptResponse\x12f\n" +
	"\x11RespondPermission\x12'.harnessapi.v1.RespondPermissionRequest\x1a(.harnessapi.v1.RespondPermissionResponse\x12Q\n" +
	"\n" +
	"EndSession\x12 .harnessapi.v1.EndSessionRequest\x1a!.harnessapi.v1.EndSessionResponse\x12Q\n" +
	"\n" +
	"GetSession\x12 .harnessapi.v1.GetSessionRequest\x1a!.harnessapi.v1.GetSessionResponse\x12W\n" +
	"\fListSessions\x12\".harnessapi.v1.ListSessionsRequest\x1a#.harnessapi.v1.ListSessionsResponse\x12Z\n" +
	"\rListTemplates\x12#.harnessapi.v1.ListTemplatesRequest\x1a$.harnessapi.v1.ListTemplatesResponse\x12Q\n" +
	"\n" +
	"ListEvents\x12 .harnessapi.v1.ListEventsRequest\x1a!.harnessapi.v1.ListEventsResponse\x12P\n" +
	"\tSubscribe\x12\x1f.harnessapi.v1.SubscribeRequest\x1a .harnessapi.v1.SubscribeResponse0\x01B:Z8github.com/pomerium/agentops/harness/api/pb;harnessapipbb\x06proto3"

var (
	file_harnessapi_v1_harnessapi_proto_rawDescOnce sync.Once
	file_harnessapi_v1_harnessapi_proto_rawDescData []byte
)

func file_harnessapi_v1_harnessapi_proto_rawDescGZIP() []byte {
	file_harnessapi_v1_harnessapi_proto_rawDescOnce.Do(func() {
		file_harnessapi_v1_harnessapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_harnessapi_v1_harnessapi_proto_rawDesc), len(file_harnessapi_v1_harnessapi_proto_rawDesc)))
	})
	return file_harnessapi_v1_harnessapi_proto_rawDescData
}

var file_harnessapi_v1_harnessapi_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_harnessapi_v1_harnessapi_proto_goTypes = []any{
	(*ErrorInfo)(nil),                 // 0: harnessapi.v1.ErrorInfo
	(*SessionRef)(nil),                // 1: harnessapi.v1.SessionRef
	(*SessionView)(nil),               // 2: harnessapi.v1.SessionView
	(*Event)(nil),                     // 3: harnessapi.v1.Event
	(*TemplateSummary)(nil),           // 4: harnessapi.v1.TemplateSummary
	(*CreateSessionRequest)(nil),      // 5: harnessapi.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),     // 6: harnessapi.v1.CreateSessionResponse
	(*PromptRequest)(nil),             // 7: harnessapi.v1.PromptRequest
	(*PromptResponse)(nil),            // 8: harnessapi.v1.PromptResponse
	(*RespondPermissionRequest)(nil),  // 9: harnessapi.v1.RespondPermissionRequest
	(*RespondPermissionResponse)(nil), // 10: harnessapi.v1.RespondPermissionResponse
	(*EndSessionRequest)(nil),         // 11: harnessapi.v1.EndSessionRequest
	(*EndSessionResponse)(nil),        // 12: harnessapi.v1.EndSessionResponse
	(*GetSessionRequest)(nil),         // 13: harnessapi.v1.GetSessionRequest
	(*GetSessionResponse)(nil),        // 14: harnessapi.v1.GetSessionResponse
	(*ListSessionsRequest)(nil),       // 15: harnessapi.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),      // 16: harnessapi.v1.ListSessionsResponse
	(*ListTemplatesRequest)(nil),      // 17: harnessapi.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),     // 18: harnessapi.v1.ListTemplatesResponse
	(*ListEventsRequest)(nil),         // 19: harnessapi.v1.ListEventsRequest
	(*ListEventsResponse)(nil),        // 20: harnessapi.v1.ListEventsResponse
	(*SubscribeRequest)(nil),          // 21: harnessapi.v1.SubscribeRequest
	(*SubscribeResponse)(nil),         // 22: harnessapi.v1.SubscribeResponse
	(*timestamppb.Timestamp)(nil),     // 23: google.protobuf.Timestamp
}
var file_harnessapi_v1_harnessapi_proto_depIdxs = []int32{
	23, // 0: harnessapi.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 1: harnessapi.v1.CreateSessionResponse.session:type_name -> harnessapi.v1.SessionView
	1,  // 2: harnessapi.v1.PromptRequest.ref:type_name -> harnessapi.v1.SessionRef
	1,  // 3: harnessapi.v1.RespondPermissionRequest.ref:type_name -> harnessapi.v1.SessionRef
	1,  // 4: harnessapi.v1.EndSessionRequest.ref:type_name -> harnessapi.v1.SessionRef
	1,  // 5: harnessapi.v1.GetSessionRequest.ref:type_name -> harnessapi.v1.SessionRef
	2,  // 6: harnessapi.v1.GetSessionResponse.session:type_name -> harnessapi.v1.SessionView
	23, // 7: harnessapi.v1.ListSessionsRequest.updated_since:type_name -> google.protobuf.Timestamp
	2,  // 8: harnessapi.v1.ListSessionsResponse.sessions:type_name -> harnessapi.v1.SessionView
	4,  // 9: harnessapi.v1.ListTemplatesResponse.templates:type_name -> harnessapi.v1.TemplateSummary
	1,  // 10: harnessapi.v1.ListEventsRequest.ref:type_name -> harnessapi.v1.SessionRef
	3,  // 11: harnessapi.v1.ListEventsResponse.events:type_name -> harnessapi.v1.Event
	1,  // 12: harnessapi.v1.SubscribeRequest.ref:type_name -> harnessapi.v1.SessionRef
	3,  // 13: harnessapi.v1.SubscribeResponse.event:type_name -> harnessapi.v1.Event
	5,  // 14: harnessapi.v1.HarnessAPIService.CreateSession:input_type -> harnessapi.v1.CreateSessionRequest
	7,  // 15: harnessapi.v1.HarnessAPIService.Prompt:input_type -> harnessapi.v1.PromptRequest
	9,  // 16: harnessapi.v1.HarnessAPIService.RespondPermission:input_type -> harnessapi.v1.RespondPermissionRequest
	11, // 17: harnessapi.v1.HarnessAPIService.EndSession:input_type -> harnessapi.v1.EndSessionRequest
	13, // 18: harnessapi.v1.HarnessAPIService.GetSession:input_type -> harnessapi.v1.GetSessionRequest
	15, // 19: harnessapi.v1.HarnessAPIService.ListSessions:input_type -> harnessapi.v1.ListSessionsRequest
	17, // 20: harnessapi.v1.HarnessAPIService.ListTemplates:input_type -> harnessapi.v1.ListTemplatesRequest
	19, // 21: harnessapi.v1.HarnessAPIService.ListEvents:input_type -> harnessapi.v1.ListEventsRequest
	21, // 22: harnessapi.v1.HarnessAPIService.Subscribe:input_type -> harnessapi.v1.SubscribeRequest
	6,  // 23: harnessapi.v1.HarnessAPIService.CreateSession:output_type -> harnessapi.v1.CreateSessionResponse
	8,  // 24: harnessapi.v1.HarnessAPIService.Prompt:output_type -> harnessapi.v1.PromptResponse
	10, // 25: harnessapi.v1.HarnessAPIService.RespondPermission:output_type -> harnessapi.v1.RespondPermissionResponse
	12, // 26: harnessapi.v1.HarnessAPIService.EndSession:output_type -> harnessapi.v1.EndSessionResponse
	14, // 27: harnessapi.v1.HarnessAPIService.GetSession:output_type -> harnessapi.v1.GetSessionResponse
	16, // 28: harnessapi.v1.HarnessAPIService.ListSessions:output_type -> harnessapi.v1.ListSessionsResponse
	18, // 29: harnessapi.v1.HarnessAPIService.ListTemplates:output_type -> harnessapi.v1.ListTemplatesResponse
	20, // 30: harnessapi.v1.HarnessAPIService.ListEvents:output_type -> harnessapi.v1.ListEventsResponse
	22, // 31: harnessapi.v1.HarnessAPIService.Subscribe:output_type -> harnessapi.v1.SubscribeResponse
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_harnessapi_v1_harnessapi_proto_init() }
func file_harnessapi_v1_harnessapi_proto_init() {
	if File_harnessapi_v1_harnessapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_harnessapi_v1_harnessapi_proto_rawDesc), len(file_harnessapi_v1_harnessapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_harnessapi_v1_harnessapi_proto_goTypes,
		DependencyIndexes: file_harnessapi_v1_harnessapi_proto_depIdxs,
		MessageInfos:      file_harnessapi_v1_harnessapi_proto_msgTypes,
	}.Build()
	File_harnessapi_v1_harnessapi_proto = out.File
	file_harnessapi_v1_harnessapi_proto_goTypes = nil
	file_harnessapi_v1_harnessapi_proto_depIdxs = nil
}
