apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxTemplate
metadata:
  name: hello
spec:
  podTemplate:
    spec:
      containers:
        - name: sidecar
          env:
            - name: SIDECAR_HTTP_ANTHROPIC_UPSTREAM_URL
              value: https://anthropic.agentops.example.com
            - name: SIDECAR_AGENTIC_AS_URL
              value: https://agentic.agentops.example.com
            - name: SIDECAR_HARNESS_URL
              value: https://harness.agentops.example.com
            - name: SIDECAR_HTTP_ANTHROPIC_DIAL_ADDRESS
              value: pomerium-proxy.agentops-pomerium.svc.cluster.local:443
            - name: SIDECAR_AGENTIC_AS_DIAL_ADDRESS
              value: pomerium-proxy.agentops-pomerium.svc.cluster.local:443
            - name: SIDECAR_HARNESS_DIAL_ADDRESS
              value: pomerium-proxy.agentops-pomerium.svc.cluster.local:443
