// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agentlink/v1/agentlink.proto

package agentlinkpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentLinkService_Attach_FullMethodName  = "/agentlink.v1.AgentLinkService/Attach"
	AgentLinkService_AgentIO_FullMethodName = "/agentlink.v1.AgentLinkService/AgentIO"
)

// AgentLinkServiceClient is the client API for AgentLinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentLinkService connects the manager to the sidecar in a sandbox pod.
//
// The manager serves this service. The sidecar dials it through a Pomerium
// route and uses the agentic run token as its bearer token. The sidecar is the
// gRPC client of each RPC. The manager sends its directives on the streams that
// the sidecar opens.
//
// The manager gets the run ID and the pod identity only from the
// X-Pomerium-Jwt-Assertion header. Messages do not carry identity. If the
// asserted pod is not the pod of the run, the manager refuses the stream.
type AgentLinkServiceClient interface {
	// Attach is the control stream of a run. A run has one live Attach stream.
	// The manager refuses a second one. Attach carries heartbeats, status and
	// directives. After a drop, the sidecar opens a new Attach stream with
	// backoff.
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SidecarFrame, ManagerFrame], error)
	// AgentIO carries the agent session between the manager and the runner. The
	// runner is the ACP client of the agent. It sends events, and the manager
	// sends commands. The sidecar passes the frames through without a change.
	//
	// The sidecar opens AgentIO after SpawnAgent. After a drop, the sidecar opens
	// it again, and the runner sends again the events that the manager did not
	// consume. A run has one live AgentIO stream. A new stream replaces the old
	// one.
	AgentIO(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentIOFrame, AgentIOFrame], error)
}

type agentLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentLinkServiceClient(cc grpc.ClientConnInterface) AgentLinkServiceClient {
	return &agentLinkServiceClient{cc}
}

func (c *agentLinkServiceClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SidecarFrame, ManagerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLinkService_ServiceDesc.Streams[0], AgentLinkService_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SidecarFrame, ManagerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLinkService_AttachClient = grpc.BidiStreamingClient[SidecarFrame, ManagerFrame]

func (c *agentLinkServiceClient) AgentIO(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentIOFrame, AgentIOFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLinkService_ServiceDesc.Streams[1], AgentLinkService_AgentIO_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentIOFrame, AgentIOFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLinkService_AgentIOClient = grpc.BidiStreamingClient[AgentIOFrame, AgentIOFrame]

// AgentLinkServiceServer is the server API for AgentLinkService service.
// All implementations must embed UnimplementedAgentLinkServiceServer
// for forward compatibility.
//
// AgentLinkService connects the manager to the sidecar in a sandbox pod.
//
// The manager serves this service. The sidecar dials it through a Pomerium
// route and uses the agentic run token as its bearer token. The sidecar is the
// gRPC client of each RPC. The manager sends its directives on the streams that
// the sidecar opens.
//
// The manager gets the run ID and the pod identity only from the
// X-Pomerium-Jwt-Assertion header. Messages do not carry identity. If the
// asserted pod is not the pod of the run, the manager refuses the stream.
type AgentLinkServiceServer interface {
	// Attach is the control stream of a run. A run has one live Attach stream.
	// The manager refuses a second one. Attach carries heartbeats, status and
	// directives. After a drop, the sidecar opens a new Attach stream with
	// backoff.
	Attach(grpc.BidiStreamingServer[SidecarFrame, ManagerFrame]) error
	// AgentIO carries the agent session between the manager and the runner. The
	// runner is the ACP client of the agent. It sends events, and the manager
	// sends commands. The sidecar passes the frames through without a change.
	//
	// The sidecar opens AgentIO after SpawnAgent. After a drop, the sidecar opens
	// it again, and the runner sends again the events that the manager did not
	// consume. A run has one live AgentIO stream. A new stream replaces the old
	// one.
	AgentIO(grpc.BidiStreamingServer[AgentIOFrame, AgentIOFrame]) error
	mustEmbedUnimplementedAgentLinkServiceServer()
}

// UnimplementedAgentLinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentLinkServiceServer struct{}

func (UnimplementedAgentLinkServiceServer) Attach(grpc.BidiStreamingServer[SidecarFrame, ManagerFrame]) error {
	return status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedAgentLinkServiceServer) AgentIO(grpc.BidiStreamingServer[AgentIOFrame, AgentIOFrame]) error {
	return status.Error(codes.Unimplemented, "method AgentIO not implemented")
}
func (UnimplementedAgentLinkServiceServer) mustEmbedUnimplementedAgentLinkServiceServer() {}
func (UnimplementedAgentLinkServiceServer) testEmbeddedByValue()                          {}

// UnsafeAgentLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentLinkServiceServer will
// result in compilation errors.
type UnsafeAgentLinkServiceServer interface {
	mustEmbedUnimplementedAgentLinkServiceServer()
}

func RegisterAgentLinkServiceServer(s grpc.ServiceRegistrar, srv AgentLinkServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentLinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentLinkService_ServiceDesc, srv)
}

func _AgentLinkService_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLinkServiceServer).Attach(&grpc.GenericServerStream[SidecarFrame, ManagerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLinkService_AttachServer = grpc.BidiStreamingServer[SidecarFrame, ManagerFrame]

func _AgentLinkService_AgentIO_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLinkServiceServer).AgentIO(&grpc.GenericServerStream[AgentIOFrame, AgentIOFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLinkService_AgentIOServer = grpc.BidiStreamingServer[AgentIOFrame, AgentIOFrame]

// AgentLinkService_ServiceDesc is the grpc.ServiceDesc for AgentLinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentlink.v1.AgentLinkService",
	HandlerType: (*AgentLinkServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _AgentLinkService_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AgentIO",
			Handler:       _AgentLinkService_AgentIO_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentlink/v1/agentlink.proto",
}
