// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agentlink/v1/agentlink.proto

package agentlinkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status_State int32

const (
	Status_STATE_UNSPECIFIED Status_State = 0
	Status_STATE_STARTING    Status_State = 1 // envoy is starting
	Status_STATE_READY       Status_State = 2 // envoy serves; this is also the heartbeat
	Status_STATE_ERROR       Status_State = 3 // the sidecar failed; it does not recover
)

// Enum value maps for Status_State.
var (
	Status_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_STARTING",
		2: "STATE_READY",
		3: "STATE_ERROR",
	}
	Status_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_STARTING":    1,
		"STATE_READY":       2,
		"STATE_ERROR":       3,
	}
)

func (x Status_State) Enum() *Status_State {
	p := new(Status_State)
	*p = x
	return p
}

func (x Status_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_State) Descriptor() protoreflect.EnumDescriptor {
	return file_agentlink_v1_agentlink_proto_enumTypes[0].Descriptor()
}

func (Status_State) Type() protoreflect.EnumType {
	return &file_agentlink_v1_agentlink_proto_enumTypes[0]
}

func (x Status_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_State.Descriptor instead.
func (Status_State) EnumDescriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{7, 0}
}

type SidecarFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SidecarFrame_Hello
	//	*SidecarFrame_Status
	//	*SidecarFrame_Exited
	Msg           isSidecarFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidecarFrame) Reset() {
	*x = SidecarFrame{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidecarFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidecarFrame) ProtoMessage() {}

func (x *SidecarFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidecarFrame.ProtoReflect.Descriptor instead.
func (*SidecarFrame) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{0}
}

func (x *SidecarFrame) GetMsg() isSidecarFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SidecarFrame) GetHello() *SidecarHello {
	if x != nil {
		if x, ok := x.Msg.(*SidecarFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *SidecarFrame) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Msg.(*SidecarFrame_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *SidecarFrame) GetExited() *AgentExited {
	if x != nil {
		if x, ok := x.Msg.(*SidecarFrame_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

type isSidecarFrame_Msg interface {
	isSidecarFrame_Msg()
}

type SidecarFrame_Hello struct {
	Hello *SidecarHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // first frame of each stream, sent once
}

type SidecarFrame_Status struct {
	Status *Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"` // state changes and heartbeats
}

type SidecarFrame_Exited struct {
	Exited *AgentExited `protobuf:"bytes,3,opt,name=exited,proto3,oneof"` // the agent process stopped
}

func (*SidecarFrame_Hello) isSidecarFrame_Msg() {}

func (*SidecarFrame_Status) isSidecarFrame_Msg() {}

func (*SidecarFrame_Exited) isSidecarFrame_Msg() {}

type ManagerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ManagerFrame_HelloAck
	//	*ManagerFrame_Spawn
	//	*ManagerFrame_Shutdown
	//	*ManagerFrame_Heartbeat
	Msg           isManagerFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerFrame) Reset() {
	*x = ManagerFrame{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerFrame) ProtoMessage() {}

func (x *ManagerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerFrame.ProtoReflect.Descriptor instead.
func (*ManagerFrame) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerFrame) GetMsg() isManagerFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ManagerFrame) GetHelloAck() *ManagerHelloAck {
	if x != nil {
		if x, ok := x.Msg.(*ManagerFrame_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ManagerFrame) GetSpawn() *SpawnAgent {
	if x != nil {
		if x, ok := x.Msg.(*ManagerFrame_Spawn); ok {
			return x.Spawn
		}
	}
	return nil
}

func (x *ManagerFrame) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Msg.(*ManagerFrame_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *ManagerFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ManagerFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isManagerFrame_Msg interface {
	isManagerFrame_Msg()
}

type ManagerFrame_HelloAck struct {
	HelloAck *ManagerHelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"` // first frame of each stream, sent once
}

type ManagerFrame_Spawn struct {
	Spawn *SpawnAgent `protobuf:"bytes,2,opt,name=spawn,proto3,oneof"` // start the agent
}

type ManagerFrame_Shutdown struct {
	// Ends the session. The sidecar stops the agent and envoy. Then it waits
	// until the pod is deleted. It does not exit, because the kubelet restarts
	// a container that exits. The manager deletes the pod.
	Shutdown *Shutdown `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

type ManagerFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"` // the manager is alive
}

func (*ManagerFrame_HelloAck) isManagerFrame_Msg() {}

func (*ManagerFrame_Spawn) isManagerFrame_Msg() {}

func (*ManagerFrame_Shutdown) isManagerFrame_Msg() {}

func (*ManagerFrame_Heartbeat) isManagerFrame_Msg() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{2}
}

type SidecarHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // 1 is the only version
	// Counts the Attach streams since the pod started. The first is 1. Use it
	// only for logs and metrics.
	Attempt uint32 `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// True on a new Attach stream if the agent survived the drop.
	AgentRunning  bool `protobuf:"varint,3,opt,name=agent_running,json=agentRunning,proto3" json:"agent_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidecarHello) Reset() {
	*x = SidecarHello{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidecarHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidecarHello) ProtoMessage() {}

func (x *SidecarHello) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidecarHello.ProtoReflect.Descriptor instead.
func (*SidecarHello) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{3}
}

func (x *SidecarHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *SidecarHello) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *SidecarHello) GetAgentRunning() bool {
	if x != nil {
		return x.AgentRunning
	}
	return false
}

type ManagerHelloAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// The sidecar sends Status at least once in each interval. The manager
	// declares the link dead after heartbeat_miss_limit intervals without a
	// frame.
	HeartbeatSeconds   uint32         `protobuf:"varint,2,opt,name=heartbeat_seconds,json=heartbeatSeconds,proto3" json:"heartbeat_seconds,omitempty"`         // default 20
	HeartbeatMissLimit uint32         `protobuf:"varint,3,opt,name=heartbeat_miss_limit,json=heartbeatMissLimit,proto3" json:"heartbeat_miss_limit,omitempty"` // default 3
	Config             *SandboxConfig `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ManagerHelloAck) Reset() {
	*x = ManagerHelloAck{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerHelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerHelloAck) ProtoMessage() {}

func (x *ManagerHelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerHelloAck.ProtoReflect.Descriptor instead.
func (*ManagerHelloAck) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{4}
}

func (x *ManagerHelloAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ManagerHelloAck) GetHeartbeatSeconds() uint32 {
	if x != nil {
		return x.HeartbeatSeconds
	}
	return 0
}

func (x *ManagerHelloAck) GetHeartbeatMissLimit() uint32 {
	if x != nil {
		return x.HeartbeatMissLimit
	}
	return 0
}

func (x *ManagerHelloAck) GetConfig() *SandboxConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// SandboxConfig is the configuration for one session. A warm-pool pod starts
// before its session exists, so it gets this configuration from the manager.
// The sidecar applies it once. A new Attach stream sends it again. The sidecar
// ignores it, because envoy is already running.
//
// Endpoints that are the same for each session stay in the env of the pod.
// The sidecar uses both sets. If one name is in both sets, the sidecar refuses
// the configuration.
type SandboxConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*ProxiedEndpoint     `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxConfig) Reset() {
	*x = SandboxConfig{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxConfig) ProtoMessage() {}

func (x *SandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxConfig.ProtoReflect.Descriptor instead.
func (*SandboxConfig) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{5}
}

func (x *SandboxConfig) GetEndpoints() []*ProxiedEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// ProxiedEndpoint is a loopback listener that envoy serves to the agent. Envoy
// sends each request to upstream_url and adds the agentic run token. The agent
// does not see a credential.
type ProxiedEndpoint struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ListenPort  uint32                 `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	UpstreamUrl string                 `protobuf:"bytes,3,opt,name=upstream_url,json=upstreamUrl,proto3" json:"upstream_url,omitempty"`
	// The host:port that envoy dials instead of the host of upstream_url. SNI
	// and Host still come from upstream_url. Use it when the public host name
	// does not resolve in the cluster.
	DialAddress   string `protobuf:"bytes,4,opt,name=dial_address,json=dialAddress,proto3" json:"dial_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxiedEndpoint) Reset() {
	*x = ProxiedEndpoint{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxiedEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxiedEndpoint) ProtoMessage() {}

func (x *ProxiedEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxiedEndpoint.ProtoReflect.Descriptor instead.
func (*ProxiedEndpoint) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{6}
}

func (x *ProxiedEndpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProxiedEndpoint) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *ProxiedEndpoint) GetUpstreamUrl() string {
	if x != nil {
		return x.UpstreamUrl
	}
	return ""
}

func (x *ProxiedEndpoint) GetDialAddress() string {
	if x != nil {
		return x.DialAddress
	}
	return ""
}

type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State Status_State           `protobuf:"varint,1,opt,name=state,proto3,enum=agentlink.v1.Status_State" json:"state,omitempty"`
	// Set on STATE_ERROR. Examples: envoy_exited, runner_unreachable,
	// token_terminal:<reason>, agentio_resume_invalid, agentio_stream_mismatch.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{7}
}

func (x *Status) GetState() Status_State {
	if x != nil {
		return x.State
	}
	return Status_STATE_UNSPECIFIED
}

func (x *Status) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// AgentExited tells the manager that the agent process stopped. The sidecar
// sends it after the manager acks all output of the agent.
type AgentExited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExited) Reset() {
	*x = AgentExited{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExited) ProtoMessage() {}

func (x *AgentExited) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExited.ProtoReflect.Descriptor instead.
func (*AgentExited) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{8}
}

func (x *AgentExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// SpawnAgent starts the agent through the runner. The sidecar starts one agent
// at most.
type SpawnAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the AgentIO byte stream. The manager makes a new random ID for
	// each run. Each AgentIOOpen must contain it.
	StreamId      []byte `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnAgent) Reset() {
	*x = SpawnAgent{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAgent) ProtoMessage() {}

func (x *SpawnAgent) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAgent.ProtoReflect.Descriptor instead.
func (*SpawnAgent) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{9}
}

func (x *SpawnAgent) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{10}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// AgentIOFrame carries the ACP bytes. Both directions use the same rules.
//
// Each side counts the bytes that it sends. The first byte is 1. Each side
// acks the bytes that it gets from its peer. A sender keeps the bytes that the
// peer did not ack. It keeps at most 8 MiB plus one frame. When it has that
// many, it stops until the peer acks. If a receiver gets more, it ends the
// stream with a protocol error.
//
// On each open, each side sends Open with the last byte that it consumed. The
// peer then sends again all bytes after that byte. If the peer no longer has
// them, the stream ends with an error. A frame carries at most 64 KiB.
type AgentIOFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentIOFrame_Open
	//	*AgentIOFrame_Data
	//	*AgentIOFrame_Ack
	Msg           isAgentIOFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIOFrame) Reset() {
	*x = AgentIOFrame{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIOFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIOFrame) ProtoMessage() {}

func (x *AgentIOFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIOFrame.ProtoReflect.Descriptor instead.
func (*AgentIOFrame) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{11}
}

func (x *AgentIOFrame) GetMsg() isAgentIOFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentIOFrame) GetOpen() *AgentIOOpen {
	if x != nil {
		if x, ok := x.Msg.(*AgentIOFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *AgentIOFrame) GetData() *AgentIOData {
	if x != nil {
		if x, ok := x.Msg.(*AgentIOFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *AgentIOFrame) GetAck() *AgentIOAck {
	if x != nil {
		if x, ok := x.Msg.(*AgentIOFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isAgentIOFrame_Msg interface {
	isAgentIOFrame_Msg()
}

type AgentIOFrame_Open struct {
	Open *AgentIOOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"` // first frame of each side, sent once
}

type AgentIOFrame_Data struct {
	Data *AgentIOData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type AgentIOFrame_Ack struct {
	Ack *AgentIOAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*AgentIOFrame_Open) isAgentIOFrame_Msg() {}

func (*AgentIOFrame_Data) isAgentIOFrame_Msg() {}

func (*AgentIOFrame_Ack) isAgentIOFrame_Msg() {}

type AgentIOOpen struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The last byte of the peer that this side consumed. The peer sends again
	// from the byte after it.
	Consumed uint64 `protobuf:"varint,1,opt,name=consumed,proto3" json:"consumed,omitempty"`
	// Must be equal to SpawnAgent.stream_id. If it is different, the offsets are
	// for a different stream, and the stream ends with an error.
	StreamId      []byte `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIOOpen) Reset() {
	*x = AgentIOOpen{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIOOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIOOpen) ProtoMessage() {}

func (x *AgentIOOpen) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIOOpen.ProtoReflect.Descriptor instead.
func (*AgentIOOpen) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{12}
}

func (x *AgentIOOpen) GetConsumed() uint64 {
	if x != nil {
		return x.Consumed
	}
	return 0
}

func (x *AgentIOOpen) GetStreamId() []byte {
	if x != nil {
		return x.StreamId
	}
	return nil
}

type AgentIOData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // the number of the last byte in payload
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIOData) Reset() {
	*x = AgentIOData{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIOData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIOData) ProtoMessage() {}

func (x *AgentIOData) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIOData.ProtoReflect.Descriptor instead.
func (*AgentIOData) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{13}
}

func (x *AgentIOData) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AgentIOData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AgentIOAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The last byte that this side consumed. It is cumulative. Each side acks
	// after each 512 KiB of new bytes, and at least every 500 ms while new bytes
	// arrive.
	Consumed      uint64 `protobuf:"varint,1,opt,name=consumed,proto3" json:"consumed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIOAck) Reset() {
	*x = AgentIOAck{}
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIOAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIOAck) ProtoMessage() {}

func (x *AgentIOAck) ProtoReflect() protoreflect.Message {
	mi := &file_agentlink_v1_agentlink_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIOAck.ProtoReflect.Descriptor instead.
func (*AgentIOAck) Descriptor() ([]byte, []int) {
	return file_agentlink_v1_agentlink_proto_rawDescGZIP(), []int{14}
}

func (x *AgentIOAck) GetConsumed() uint64 {
	if x != nil {
		return x.Consumed
	}
	return 0
}

var File_agentlink_v1_agentlink_proto protoreflect.FileDescriptor

const file_agentlink_v1_agentlink_proto_rawDesc = "" +
	"\n" +
	"\x1cagentlink/v1/agentlink.proto\x12\fagentlink.v1\"\xae\x01\n" +
	"\fSidecarFrame\x122\n" +
	"\x05hello\x18\x01 \x01(\v2\x1a.agentlink.v1.SidecarHelloH\x00R\x05hello\x12.\n" +
	"\x06status\x18\x02 \x01(\v2\x14.agentlink.v1.StatusH\x00R\x06status\x123\n" +
	"\x06exited\x18\x03 \x01(\v2\x19.agentlink.v1.AgentExitedH\x00R\x06exitedB\x05\n" +
	"\x03msg\"\xf4\x01\n" +
	"\fManagerFrame\x12<\n" +
	"\thello_ack\x18\x01 \x01(\v2\x1d.agentlink.v1.ManagerHelloAckH\x00R\bhelloAck\x120\n" +
	"\x05spawn\x18\x02 \x01(\v2\x18.agentlink.v1.SpawnAgentH\x00R\x05spawn\x124\n" +
	"\bshutdown\x18\x03 \x01(\v2\x16.agentlink.v1.ShutdownH\x00R\bshutdown\x127\n" +
	"\theartbeat\x18\x04 \x01(\v2\x17.agentlink.v1.HeartbeatH\x00R\theartbeatB\x05\n" +
	"\x03msg\"\v\n" +
	"\tHeartbeat\"x\n" +
	"\fSidecarHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\rR\aattempt\x12#\n" +
	"\ragent_running\x18\x03 \x01(\bR\fagentRunning\"\xd0\x01\n" +
	"\x0fManagerHelloAck\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12+\n" +
	"\x11heartbeat_seconds\x18\x02 \x01(\rR\x10heartbeatSeconds\x120\n" +
	"\x14heartbeat_miss_limit\x18\x03 \x01(\rR\x12heartbeatMissLimit\x123\n" +
	"\x06config\x18\x04 \x01(\v2\x1b.agentlink.v1.SandboxConfigR\x06config\"L\n" +
	"\rSandboxConfig\x12;\n" +
	"\tendpoints\x18\x01 \x03(\v2\x1d.agentlink.v1.ProxiedEndpointR\tendpoints\"\x8c\x01\n" +
	"\x0fProxiedEndpoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\rR\n" +
	"listenPort\x12!\n" +
	"\fupstream_url\x18\x03 \x01(\tR\vupstreamUrl\x12!\n" +
	"\fdial_address\x18\x04 \x01(\tR\vdialAddress\"\xa8\x01\n" +
	"\x06Status\x120\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.agentlink.v1.Status.StateR\x05state\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"T\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATE_STARTING\x10\x01\x12\x0f\n" +
	"\vSTATE_READY\x10\x02\x12\x0f\n" +
	"\vSTATE_ERROR\x10\x03\"*\n" +
	"\vAgentExited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\")\n" +
	"\n" +
	"SpawnAgent\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\fR\bstreamId\"\"\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xa5\x01\n" +
	"\fAgentIOFrame\x12/\n" +
	"\x04open\x18\x01 \x01(\v2\x19.agentlink.v1.AgentIOOpenH\x00R\x04open\x12/\n" +
	"\x04data\x18\x02 \x01(\v2\x19.agentlink.v1.AgentIODataH\x00R\x04data\x12,\n" +
	"\x03ack\x18\x03 \x01(\v2\x18.agentlink.v1.AgentIOAckH\x00R\x03ackB\x05\n" +
	"\x03msg\"F\n" +
	"\vAgentIOOpen\x12\x1a\n" +
	"\bconsumed\x18\x01 \x01(\x04R\bconsumed\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\fR\bstreamId\"9\n" +
	"\vAgentIOData\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"(\n" +
	"\n" +
	"AgentIOAck\x12\x1a\n" +
	"\bconsumed\x18\x01 \x01(\x04R\bconsumed2\x9f\x01\n" +
	"\x10AgentLinkService\x12D\n" +
	"\x06Attach\x12\x1a.agentlink.v1.SidecarFrame\x1a\x1a.agentlink.v1.ManagerFrame(\x010\x01\x12E\n" +
	"\aAgentIO\x12\x1a.agentlink.v1.AgentIOFrame\x1a\x1a.agentlink.v1.AgentIOFrame(\x010\x01BHZFgithub.com/pomerium/agentops/harness/internal/agentlink/pb;agentlinkpbb\x06proto3"

var (
	file_agentlink_v1_agentlink_proto_rawDescOnce sync.Once
	file_agentlink_v1_agentlink_proto_rawDescData []byte
)

func file_agentlink_v1_agentlink_proto_rawDescGZIP() []byte {
	file_agentlink_v1_agentlink_proto_rawDescOnce.Do(func() {
		file_agentlink_v1_agentlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentlink_v1_agentlink_proto_rawDesc), len(file_agentlink_v1_agentlink_proto_rawDesc)))
	})
	return file_agentlink_v1_agentlink_proto_rawDescData
}

var file_agentlink_v1_agentlink_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agentlink_v1_agentlink_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_agentlink_v1_agentlink_proto_goTypes = []any{
	(Status_State)(0),       // 0: agentlink.v1.Status.State
	(*SidecarFrame)(nil),    // 1: agentlink.v1.SidecarFrame
	(*ManagerFrame)(nil),    // 2: agentlink.v1.ManagerFrame
	(*Heartbeat)(nil),       // 3: agentlink.v1.Heartbeat
	(*SidecarHello)(nil),    // 4: agentlink.v1.SidecarHello
	(*ManagerHelloAck)(nil), // 5: agentlink.v1.ManagerHelloAck
	(*SandboxConfig)(nil),   // 6: agentlink.v1.SandboxConfig
	(*ProxiedEndpoint)(nil), // 7: agentlink.v1.ProxiedEndpoint
	(*Status)(nil),          // 8: agentlink.v1.Status
	(*AgentExited)(nil),     // 9: agentlink.v1.AgentExited
	(*SpawnAgent)(nil),      // 10: agentlink.v1.SpawnAgent
	(*Shutdown)(nil),        // 11: agentlink.v1.Shutdown
	(*AgentIOFrame)(nil),    // 12: agentlink.v1.AgentIOFrame
	(*AgentIOOpen)(nil),     // 13: agentlink.v1.AgentIOOpen
	(*AgentIOData)(nil),     // 14: agentlink.v1.AgentIOData
	(*AgentIOAck)(nil),      // 15: agentlink.v1.AgentIOAck
}
var file_agentlink_v1_agentlink_proto_depIdxs = []int32{
	4,  // 0: agentlink.v1.SidecarFrame.hello:type_name -> agentlink.v1.SidecarHello
	8,  // 1: agentlink.v1.SidecarFrame.status:type_name -> agentlink.v1.Status
	9,  // 2: agentlink.v1.SidecarFrame.exited:type_name -> agentlink.v1.AgentExited
	5,  // 3: agentlink.v1.ManagerFrame.hello_ack:type_name -> agentlink.v1.ManagerHelloAck
	10, // 4: agentlink.v1.ManagerFrame.spawn:type_name -> agentlink.v1.SpawnAgent
	11, // 5: agentlink.v1.ManagerFrame.shutdown:type_name -> agentlink.v1.Shutdown
	3,  // 6: agentlink.v1.ManagerFrame.heartbeat:type_name -> agentlink.v1.Heartbeat
	6,  // 7: agentlink.v1.ManagerHelloAck.config:type_name -> agentlink.v1.SandboxConfig
	7,  // 8: agentlink.v1.SandboxConfig.endpoints:type_name -> agentlink.v1.ProxiedEndpoint
	0,  // 9: agentlink.v1.Status.state:type_name -> agentlink.v1.Status.State
	13, // 10: agentlink.v1.AgentIOFrame.open:type_name -> agentlink.v1.AgentIOOpen
	14, // 11: agentlink.v1.AgentIOFrame.data:type_name -> agentlink.v1.AgentIOData
	15, // 12: agentlink.v1.AgentIOFrame.ack:type_name -> agentlink.v1.AgentIOAck
	1,  // 13: agentlink.v1.AgentLinkService.Attach:input_type -> agentlink.v1.SidecarFrame
	12, // 14: agentlink.v1.AgentLinkService.AgentIO:input_type -> agentlink.v1.AgentIOFrame
	2,  // 15: agentlink.v1.AgentLinkService.Attach:output_type -> agentlink.v1.ManagerFrame
	12, // 16: agentlink.v1.AgentLinkService.AgentIO:output_type -> agentlink.v1.AgentIOFrame
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_agentlink_v1_agentlink_proto_init() }
func file_agentlink_v1_agentlink_proto_init() {
	if File_agentlink_v1_agentlink_proto != nil {
		return
	}
	file_agentlink_v1_agentlink_proto_msgTypes[0].OneofWrappers = []any{
		(*SidecarFrame_Hello)(nil),
		(*SidecarFrame_Status)(nil),
		(*SidecarFrame_Exited)(nil),
	}
	file_agentlink_v1_agentlink_proto_msgTypes[1].OneofWrappers = []any{
		(*ManagerFrame_HelloAck)(nil),
		(*ManagerFrame_Spawn)(nil),
		(*ManagerFrame_Shutdown)(nil),
		(*ManagerFrame_Heartbeat)(nil),
	}
	file_agentlink_v1_agentlink_proto_msgTypes[11].OneofWrappers = []any{
		(*AgentIOFrame_Open)(nil),
		(*AgentIOFrame_Data)(nil),
		(*AgentIOFrame_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentlink_v1_agentlink_proto_rawDesc), len(file_agentlink_v1_agentlink_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentlink_v1_agentlink_proto_goTypes,
		DependencyIndexes: file_agentlink_v1_agentlink_proto_depIdxs,
		EnumInfos:         file_agentlink_v1_agentlink_proto_enumTypes,
		MessageInfos:      file_agentlink_v1_agentlink_proto_msgTypes,
	}.Build()
	File_agentlink_v1_agentlink_proto = out.File
	file_agentlink_v1_agentlink_proto_goTypes = nil
	file_agentlink_v1_agentlink_proto_depIdxs = nil
}
