// Code generated by cmd/vocabgen from proto/vocabulary.yaml. DO NOT EDIT.

package wire

import (
	"connectrpc.com/connect"

	"github.com/pomerium/agentops/harness/api"
)

// published is the error set, in one table read from both directions: the name
// travels on the wire, the code is what a transport-only client sees.
//
// The name is what makes the mapping injective. Several sentinels share a code —
// a missing session and an unknown permission request are both not-found-ish,
// forbidden and quota-exceeded are both refusals — so a client branching on
// errors.Is needs the sentinel that was actually raised rather than the nearest
// code. A slice rather than two maps because the match order has to be
// deterministic: an error wrapping two sentinels must classify the same way
// every time.
var published = []struct {
	name string
	err  error
	code connect.Code
}{
	{"ErrNotFound", api.ErrNotFound, connect.CodeNotFound},
	{"ErrUnknownRequest", api.ErrUnknownRequest, connect.CodeNotFound},
	{"ErrForbidden", api.ErrForbidden, connect.CodePermissionDenied},
	{"ErrConflict", api.ErrConflict, connect.CodeAlreadyExists},
	{"ErrInvalidState", api.ErrInvalidState, connect.CodeFailedPrecondition},
	{"ErrNotRevivable", api.ErrNotRevivable, connect.CodeFailedPrecondition},
	{"ErrInvalidArgument", api.ErrInvalidArgument, connect.CodeInvalidArgument},
	{"ErrNotImplemented", api.ErrNotImplemented, connect.CodeUnimplemented},
	{"ErrUnavailable", api.ErrUnavailable, connect.CodeUnavailable},
	{"ErrQuotaExceeded", api.ErrQuotaExceeded, connect.CodeResourceExhausted},
}
