apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: claude-code-runid
  labels:
    app.kubernetes.io/name: agentops
spec:
  replicas: 1
  sandboxTemplateRef:
    name: claude-code-runid
