// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: sidecar/v1/sidecar.proto

package sidecarpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status_State int32

const (
	Status_STATE_UNSPECIFIED Status_State = 0
	Status_STATE_STARTING    Status_State = 1
	Status_STATE_READY       Status_State = 2
	Status_STATE_ERROR       Status_State = 3
)

// Enum value maps for Status_State.
var (
	Status_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_STARTING",
		2: "STATE_READY",
		3: "STATE_ERROR",
	}
	Status_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_STARTING":    1,
		"STATE_READY":       2,
		"STATE_ERROR":       3,
	}
)

func (x Status_State) Enum() *Status_State {
	p := new(Status_State)
	*p = x
	return p
}

func (x Status_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_State) Descriptor() protoreflect.EnumDescriptor {
	return file_sidecar_v1_sidecar_proto_enumTypes[0].Descriptor()
}

func (Status_State) Type() protoreflect.EnumType {
	return &file_sidecar_v1_sidecar_proto_enumTypes[0]
}

func (x Status_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_State.Descriptor instead.
func (Status_State) EnumDescriptor() ([]byte, []int) {
	return file_sidecar_v1_sidecar_proto_rawDescGZIP(), []int{5, 0}
}

type ControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlRequest_Configure
	Msg           isControlRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_v1_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *ControlRequest) GetMsg() isControlRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlRequest) GetConfigure() *Configure {
	if x != nil {
		if x, ok := x.Msg.(*ControlRequest_Configure); ok {
			return x.Configure
		}
	}
	return nil
}

type isControlRequest_Msg interface {
	isControlRequest_Msg()
}

type ControlRequest_Configure struct {
	Configure *Configure `protobuf:"bytes,1,opt,name=configure,proto3,oneof"`
}

func (*ControlRequest_Configure) isControlRequest_Msg() {}

// Configure carries the full set of HTTP endpoints the sidecar should serve.
// Endpoints defined via SIDECAR_HTTP_* environment variables on the sidecar
// container are merged in by the sidecar itself.
type Configure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*HttpEndpoint        `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configure) Reset() {
	*x = Configure{}
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configure) ProtoMessage() {}

func (x *Configure) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configure.ProtoReflect.Descriptor instead.
func (*Configure) Descriptor() ([]byte, []int) {
	return file_sidecar_v1_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *Configure) GetEndpoints() []*HttpEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// HttpEndpoint maps a localhost listener to an upstream URL, injecting the
// given headers on every proxied request. Secret credentials live only in
// `headers` and never reach the agent container.
type HttpEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique endpoint name; used for envoy resource names and status reporting.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Port of the 127.0.0.1 listener exposed to the agent container.
	ListenPort uint32 `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// Upstream scheme://host[:port]; the request path is forwarded unchanged.
	UpstreamUrl string `protobuf:"bytes,3,opt,name=upstream_url,json=upstreamUrl,proto3" json:"upstream_url,omitempty"`
	// Headers added to every upstream request (overwriting client-sent values).
	Headers       []*Header `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpEndpoint) Reset() {
	*x = HttpEndpoint{}
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpEndpoint) ProtoMessage() {}

func (x *HttpEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpEndpoint.ProtoReflect.Descriptor instead.
func (*HttpEndpoint) Descriptor() ([]byte, []int) {
	return file_sidecar_v1_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *HttpEndpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HttpEndpoint) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *HttpEndpoint) GetUpstreamUrl() string {
	if x != nil {
		return x.UpstreamUrl
	}
	return ""
}

func (x *HttpEndpoint) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_sidecar_v1_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ControlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ControlResponse_Status
	Msg           isControlResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_v1_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *ControlResponse) GetMsg() isControlResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ControlResponse) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Msg.(*ControlResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isControlResponse_Msg interface {
	isControlResponse_Msg()
}

type ControlResponse_Status struct {
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

func (*ControlResponse_Status) isControlResponse_Msg() {}

// Status reports sidecar lifecycle transitions. READY is sent once all
// listeners are live; ERROR is terminal.
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         Status_State           `protobuf:"varint,1,opt,name=state,proto3,enum=sidecar.v1.Status_State" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Endpoints     []*EndpointStatus      `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_sidecar_v1_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *Status) GetState() Status_State {
	if x != nil {
		return x.State
	}
	return Status_STATE_UNSPECIFIED
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetEndpoints() []*EndpointStatus {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type EndpointStatus struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ListenPort uint32                 `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// True when the endpoint came from SIDECAR_HTTP_* env vars rather than a
	// Configure message.
	EnvDefined    bool `protobuf:"varint,3,opt,name=env_defined,json=envDefined,proto3" json:"env_defined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointStatus) Reset() {
	*x = EndpointStatus{}
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointStatus) ProtoMessage() {}

func (x *EndpointStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_v1_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointStatus.ProtoReflect.Descriptor instead.
func (*EndpointStatus) Descriptor() ([]byte, []int) {
	return file_sidecar_v1_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *EndpointStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndpointStatus) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *EndpointStatus) GetEnvDefined() bool {
	if x != nil {
		return x.EnvDefined
	}
	return false
}

var File_sidecar_v1_sidecar_proto protoreflect.FileDescriptor

const file_sidecar_v1_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x18sidecar/v1/sidecar.proto\x12\n" +
	"sidecar.v1\"N\n" +
	"\x0eControlRequest\x125\n" +
	"\tconfigure\x18\x01 \x01(\v2\x15.sidecar.v1.ConfigureH\x00R\tconfigureB\x05\n" +
	"\x03msg\"C\n" +
	"\tConfigure\x126\n" +
	"\tendpoints\x18\x01 \x03(\v2\x18.sidecar.v1.HttpEndpointR\tendpoints\"\x94\x01\n" +
	"\fHttpEndpoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\rR\n" +
	"listenPort\x12!\n" +
	"\fupstream_url\x18\x03 \x01(\tR\vupstreamUrl\x12,\n" +
	"\aheaders\x18\x04 \x03(\v2\x12.sidecar.v1.HeaderR\aheaders\"2\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"F\n" +
	"\x0fControlResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x12.sidecar.v1.StatusH\x00R\x06statusB\x05\n" +
	"\x03msg\"\xe2\x01\n" +
	"\x06Status\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.sidecar.v1.Status.StateR\x05state\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\tendpoints\x18\x03 \x03(\v2\x1a.sidecar.v1.EndpointStatusR\tendpoints\"T\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATE_STARTING\x10\x01\x12\x0f\n" +
	"\vSTATE_READY\x10\x02\x12\x0f\n" +
	"\vSTATE_ERROR\x10\x03\"f\n" +
	"\x0eEndpointStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\rR\n" +
	"listenPort\x12\x1f\n" +
	"\venv_defined\x18\x03 \x01(\bR\n" +
	"envDefined2_\n" +
	"\x15SidecarControlService\x12F\n" +
	"\aControl\x12\x1a.sidecar.v1.ControlRequest\x1a\x1b.sidecar.v1.ControlResponse(\x010\x01B<Z:github.com/pomerium/agentops/internal/sidecar/pb;sidecarpbb\x06proto3"

var (
	file_sidecar_v1_sidecar_proto_rawDescOnce sync.Once
	file_sidecar_v1_sidecar_proto_rawDescData []byte
)

func file_sidecar_v1_sidecar_proto_rawDescGZIP() []byte {
	file_sidecar_v1_sidecar_proto_rawDescOnce.Do(func() {
		file_sidecar_v1_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidecar_v1_sidecar_proto_rawDesc), len(file_sidecar_v1_sidecar_proto_rawDesc)))
	})
	return file_sidecar_v1_sidecar_proto_rawDescData
}

var file_sidecar_v1_sidecar_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sidecar_v1_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sidecar_v1_sidecar_proto_goTypes = []any{
	(Status_State)(0),       // 0: sidecar.v1.Status.State
	(*ControlRequest)(nil),  // 1: sidecar.v1.ControlRequest
	(*Configure)(nil),       // 2: sidecar.v1.Configure
	(*HttpEndpoint)(nil),    // 3: sidecar.v1.HttpEndpoint
	(*Header)(nil),          // 4: sidecar.v1.Header
	(*ControlResponse)(nil), // 5: sidecar.v1.ControlResponse
	(*Status)(nil),          // 6: sidecar.v1.Status
	(*EndpointStatus)(nil),  // 7: sidecar.v1.EndpointStatus
}
var file_sidecar_v1_sidecar_proto_depIdxs = []int32{
	2, // 0: sidecar.v1.ControlRequest.configure:type_name -> sidecar.v1.Configure
	3, // 1: sidecar.v1.Configure.endpoints:type_name -> sidecar.v1.HttpEndpoint
	4, // 2: sidecar.v1.HttpEndpoint.headers:type_name -> sidecar.v1.Header
	6, // 3: sidecar.v1.ControlResponse.status:type_name -> sidecar.v1.Status
	0, // 4: sidecar.v1.Status.state:type_name -> sidecar.v1.Status.State
	7, // 5: sidecar.v1.Status.endpoints:type_name -> sidecar.v1.EndpointStatus
	1, // 6: sidecar.v1.SidecarControlService.Control:input_type -> sidecar.v1.ControlRequest
	5, // 7: sidecar.v1.SidecarControlService.Control:output_type -> sidecar.v1.ControlResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sidecar_v1_sidecar_proto_init() }
func file_sidecar_v1_sidecar_proto_init() {
	if File_sidecar_v1_sidecar_proto != nil {
		return
	}
	file_sidecar_v1_sidecar_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlRequest_Configure)(nil),
	}
	file_sidecar_v1_sidecar_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_v1_sidecar_proto_rawDesc), len(file_sidecar_v1_sidecar_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sidecar_v1_sidecar_proto_goTypes,
		DependencyIndexes: file_sidecar_v1_sidecar_proto_depIdxs,
		EnumInfos:         file_sidecar_v1_sidecar_proto_enumTypes,
		MessageInfos:      file_sidecar_v1_sidecar_proto_msgTypes,
	}.Build()
	File_sidecar_v1_sidecar_proto = out.File
	file_sidecar_v1_sidecar_proto_goTypes = nil
	file_sidecar_v1_sidecar_proto_depIdxs = nil
}
