// Code generated by cmd/vocabgen from proto/payloads.yaml. DO NOT EDIT.

// The payload types, which the harness marshals with encoding/json — so
// these declarations ARE the wire format, and what a client of any language
// decodes is what this file says. Keys are snake_case; a duration is a
// numeric count of nanoseconds, named with an _ns suffix.

package api

import (
	"encoding/json"
	"time"
)

// StateChanged is a session-state transition.
type StateChanged struct {
	// Old: the state the session left.
	Old SessionState `json:"old"`
	// New: the state the session is now in; the same value a GetSession would
	// report.
	New SessionState `json:"new"`
	// Reason: one of the Reason values, empty for an ordinary transition.
	Reason string `json:"reason,omitempty"`
}

// ApprovalRequired is the consent page a human has to visit before the run
// may start.
//
// The URL is platform-authoritative: a client renders it as chrome the
// agent cannot imitate, never as agent-supplied content.
type ApprovalRequired struct {
	// ApprovalURL: the consent page to deliver to the approver. Opening it lets
	// the person who follows it approve this run, so hand it only to that
	// person, and render it as chrome rather than as anything the agent said.
	ApprovalURL string `json:"approval_url"`
	// ExpiresAt: when the approval window closes. A timestamp is always
	// written, so an absent expiry reads as the zero time rather than as a
	// missing key.
	ExpiresAt time.Time `json:"expires_at"`
}

// Approved is the verified identity that let the run start.
type Approved struct {
	// ApproverSubject: the raw IdP subject reported by the authorization server
	// — email/name enrichment is a directory concern and deliberately not an AS
	// field.
	ApproverSubject string `json:"approver_subject"`
}

// LaunchStalled is an approved run whose workspace should have dialed in
// seconds later, and has not.
//
// It is on the log rather than only in the platform's own trace because it
// is the one launch observation a reader can act on, and without it the
// session sits on "waiting for approval" long after the approval — which
// reads as "nobody clicked" and sends every diagnosis to the wrong
// subsystem. The session is not lost when this arrives: the approval window
// is still open and the sandbox keeps retrying, so it reports rather than
// concludes.
type LaunchStalled struct {
	// Waited: how long the approved run has gone without its workspace
	// connecting back.
	Waited time.Duration `json:"waited_ns"`
}

// AgentMessage is one complete segment of the agent's visible output.
//
// A segment, not a chunk. The platform buffers ACP message chunks and emits
// a segment when a tool call interrupts it (final false) or when the turn
// ends (final true) — the same granularity the Slack renderer has always
// displayed, and the granularity that keeps the durable log from carrying
// one row per token. part_id addresses the segment, so a client updates a
// rendered part in place instead of diffing text.
//
// text is attacker-influenceable by construction (prompt injection). The
// platform carries it verbatim and never sanitizes it; rendering it as
// inert content — no link unfurling, no mention syntax — is the client's
// half of the contract.
type AgentMessage struct {
	// PartID: addresses this segment within the turn. A later agent_message
	// with the same part_id replaces the text of the one before, so a client
	// updates the rendered part in place.
	PartID string `json:"part_id"`
	// Text: the segment's text, verbatim from the agent. Untrusted; render it
	// as inert content.
	Text string `json:"text"`
	// Final: true on the turn's last segment, false on one a tool call
	// interrupted.
	Final bool `json:"final"`
}

// AgentThought is the agent's reasoning, when it discloses any.
type AgentThought struct {
	// Text: the reasoning, verbatim from the agent. Untrusted, like agent text.
	Text string `json:"text"`
}

// ToolCall announces a tool call or updates one already announced.
//
// Today's Slack UX (segment flush, busy indicator) is driven entirely by
// these, which is why they are on the log rather than only in the
// application trace.
type ToolCall struct {
	// ID: identifies the call within the session; an update carries the id of
	// the call it updates, and a permission_request names it as tool_call_id.
	ID string `json:"id"`
	// Title: a short human-readable name for the call, as the agent gives it.
	Title string `json:"title,omitempty"`
	// Kind: what sort of tool it is (read, edit, execute, fetch, …), passed
	// through from the agent's protocol unchanged.
	Kind string `json:"kind,omitempty"`
	// Status: where the call is, one of the ToolCallStatus values.
	Status ToolCallStatus `json:"status"`
	// InvocationMessage: the agent's own description of what it is doing, when
	// it supplies one.
	InvocationMessage string `json:"invocation_message,omitempty"`
	// ToolInput: the raw tool input as the agent sent it, when the agent
	// discloses it. Untrusted, like agent text.
	ToolInput json.RawMessage `json:"tool_input,omitempty"`
	// Update: false when this announces a new call, true for a status or result
	// update to one already announced.
	Update bool `json:"update,omitempty"`
}

// PermissionOption is one choice on a permission request.
type PermissionOption struct {
	// ID: the option's id, which RespondPermission takes as option_id.
	ID string `json:"id"`
	// Name: the option's label, as the agent offers it, for the person
	// choosing.
	Name string `json:"name"`
	// Kind: what choosing it means (allow_once, allow_always, reject_once,
	// reject_always, …), passed through from the agent's protocol unchanged.
	Kind string `json:"kind,omitempty"`
}

// PermissionRequest asks the client's principal to authorize a tool call.
// The agent is blocked until RespondPermission answers it or the deadline
// passes.
type PermissionRequest struct {
	// RequestID: identifies the request; RespondPermission takes it, and the
	// permission_resolved event that closes it carries it.
	RequestID string `json:"request_id"`
	// Summary: what the agent is asking to do, in its own words, for the person
	// deciding. Untrusted, like agent text.
	Summary string `json:"summary"`
	// Options: the choices on offer. Answer with one of their ids.
	Options []PermissionOption `json:"options"`
	// Deadline: when the request lapses unanswered; the agent is then told no,
	// and a permission_resolved event records it as expired.
	Deadline time.Time `json:"deadline"`
	// ToolCallID: the call the request belongs to.
	ToolCallID string `json:"tool_call_id,omitempty"`
}

// PermissionResolved closes a permission request, however it ended.
//
// It closes the loop after a reconnect too: a client that missed the answer
// learns it from here rather than leaving buttons live forever.
type PermissionResolved struct {
	// RequestID: the request this closes, as permission_request named it.
	RequestID string `json:"request_id"`
	// Resolution: the chosen option id, or one of the Resolution values.
	Resolution string `json:"resolution"`
}

// TurnCompleted is a turn that finished.
type TurnCompleted struct {
	// StopReason: the ACP stop reason ("end_turn", "max_tokens", "cancelled",
	// …).
	StopReason string `json:"stop_reason"`
}

// TurnFailed is a turn that died. "Why did this turn die" is a first-class
// answer, not something to reconstruct from logs.
type TurnFailed struct {
	// Reason: why the turn died, as a human-readable explanation for a person
	// or a log.
	Reason string `json:"reason"`
}

// Usage is the turn's token and cost counters, as the agent reports them.
// Chargeback is the second question every platform team asks, so these are
// on the log from day one.
type Usage struct {
	// InputTokens: prompt tokens the turn consumed.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens: tokens the agent generated.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// CachedInputTokens: prompt tokens served from the model's cache.
	CachedInputTokens int64 `json:"cached_input_tokens,omitempty"`
	// CacheCreationTokens: prompt tokens written to the model's cache.
	CacheCreationTokens int64 `json:"cache_creation_tokens,omitempty"`
	// ThoughtTokens: tokens spent on reasoning, when the model reports them
	// separately.
	ThoughtTokens int64 `json:"thought_tokens,omitempty"`
	// TotalTokens: all tokens the turn used, as the agent counts them.
	TotalTokens int64 `json:"total_tokens,omitempty"`
	// CostUSD: what the turn cost, in US dollars, as the agent reports it.
	CostUSD float64 `json:"cost_usd,omitempty"`
	// ContextWindow: how much context the agent has, when it says.
	ContextWindow int64 `json:"context_window,omitempty"`
	// ContextUsed: how much of it this turn left occupied, when it says.
	ContextUsed int64 `json:"context_used,omitempty"`
}

// IdleWarning is a quiet session, to be suspended in lead_ns unless
// something happens.
type IdleWarning struct {
	// Lead: how long until the session is suspended; a Prompt before then keeps
	// it running.
	Lead time.Duration `json:"lead_ns"`
}

// Suspended is a session whose pod is gone. The workspace and the
// conversation are not.
type Suspended struct {
	// Reason: one of the Reason values.
	Reason string `json:"reason,omitempty"`
	// RetainedFor: how long the workspace is kept before it is released.
	RetainedFor time.Duration `json:"retained_for_ns,omitempty"`
}

// Revived is a suspended session come back — same workspace, same
// conversation, new pod, new run, and a fresh human approval.
type Revived struct{}

// Released is a suspended session whose retention window lapsed and whose
// workspace was reclaimed.
type Released struct {
	// RetainedFor: how long the workspace was kept.
	RetainedFor time.Duration `json:"retained_for_ns,omitempty"`
}

// SessionEnded is the last event a session ever emits.
type SessionEnded struct {
	// Reason: one of the EndReason values.
	Reason string `json:"reason"`
	// Detail: a human-readable elaboration, empty when the reason says it all.
	// It is for a person reading a log, never for a client to branch on — that
	// is what reason is for.
	Detail string `json:"detail,omitempty"`
}

// payloadByEventType is a zero value of every payload the log carries, by
// the EventType that carries it. Nothing in the API reads it — the
// wire-conventions test walks it, so a payload added to the schema cannot
// slip past unexercised.
var payloadByEventType = map[EventType]any{
	EventStateChanged:       StateChanged{},
	EventApprovalRequired:   ApprovalRequired{},
	EventApproved:           Approved{},
	EventLaunchStalled:      LaunchStalled{},
	EventAgentMessage:       AgentMessage{},
	EventAgentThought:       AgentThought{},
	EventToolCall:           ToolCall{},
	EventPermissionRequest:  PermissionRequest{},
	EventPermissionResolved: PermissionResolved{},
	EventTurnCompleted:      TurnCompleted{},
	EventTurnFailed:         TurnFailed{},
	EventUsage:              Usage{},
	EventIdleWarning:        IdleWarning{},
	EventSuspended:          Suspended{},
	EventRevived:            Revived{},
	EventReleased:           Released{},
	EventSessionEnded:       SessionEnded{},
}
